### ISSUE TITLE
Make span naming more consistent with other languages

### ISSUE THREAD

**Issue by dashpole** [GoogleCloudPlatform/opentelemetry-operations-go#109]
Default span naming in the go exporter is `Span.<kind>.<name>`.  According to @aabmass, it is just `<name>` for python and for javascript.  Since the opentelemetry collector is written in golang, this means a python application's span naming will change if it sends to a collector vs if it sends directly to stackdriver.

**Comment by tbarker25** [comment]
This should be fixed by #155
