### ISSUE TITLE
broken imports for restructured v0.15.0 otel API packages

### ISSUE THREAD

**Issue by ptone** [GoogleCloudPlatform/opentelemetry-operations-go#122]
https://github.com/open-telemetry/opentelemetry-go/issues/1303

Seems to have broken a bunch of imports

```
github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/metric imports
	go.opentelemetry.io/otel/api/global: module go.opentelemetry.io/otel@latest found (v0.15.0), but does not contain package go.opentelemetry.io/otel/api/global
```

For reasons (of my fault/ignorance) I can't seem to get pinned .14 v to work in my go.mod file

**Comment by ptone** [comment]
I suppose this is just a matter of cutting a versioned release for go to find, using 

go get github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/metric@d8551be9a708acfb92cccad81e488e9a96434a9a

for latest commit fixed this for me

**Comment by Kun17** [comment]
I am experiencing the same issue here. And go get github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/metric@d8551be9a708acfb92cccad81e488e9a96434a9a does not work

**Comment by dashpole** [comment]
I cut the v0.15.0 release for go, so this should be fixed.
