### ISSUE TITLE
InvalidArgument: Points must be written in order.

### ISSUE THREAD

**Issue by vsekhar** [GoogleCloudPlatform/opentelemetry-operations-go#127]
After starting two local instances of my server and letting them run for about a minute, I get the following error about every minute:

```
2020/12/31 21:41:40 rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: Points must be written in order. One or more of the points specified had an older start time than the most recent point.: timeSeries[1-12]
```

Based on some earlier [comments](https://github.com/census-instrumentation/opencensus-node/issues/694#issuecomment-563896578), I tried ensuring I am setting the host and service names without success.

```go
r.peerCount = metric.Must(meter).NewInt64ValueRecorder(
		"peers",
		metric.WithDescription("Number of peers found and joined"),
	).Bind([]label.KeyValue{
		label.String("host.id", nodeName),
		label.String("service.name", "peer_service"),
		label.String("service.instance.id", nodeName),
	}...)
```

 I also tried setting the `OC_RESOURCE_LABEL=host.id=instance_123` environment variable without success.

What is the correct way to provide an instance_id when not running on GCE or GKE? Or is there some other issue here?

**Comment by punya** [comment]
Is `nodeName` the same between the two local instances of your server?

**Comment by vsekhar** [comment]
It is different. Each instance randomly generates a name suffix.

**Comment by dashpole** [comment]
Sorry for the slow response.  Which monitored resource is your metric being written to?

**Comment by dashpole** [comment]
I'm going to close this for now, but feel free to reopen if you are still having problems.  For others that find this, I would recommend using the gcp resource detector: https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/detectors/gcp.  Also, make sure the export interval of your periodic reader is at least 10 seconds.
