### ISSUE TITLE
Add unique identifier option to upload metrics within write_interval

### ISSUE THREAD

**Issue by IsaacPD** [GoogleCloudPlatform/opentelemetry-operations-go#128]
The python library for exporting to cloud monitoring contains a parameter for the metrics exporter that allows adding a unique identifier for the event where "there exist two (or more) exporters that may export to the same metric name within WRITE_INTERVAL seconds of each other." as described [in this documentation](https://google-cloud-opentelemetry.readthedocs.io/en/latest/cloud_monitoring/cloud_monitoring.html)

The code related to it is here https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/blob/7b71183b8e6cffcdbc4805687b9546f409bf0885/opentelemetry-exporter-google-cloud/src/opentelemetry/exporter/cloud_monitoring/__init__.py#L70-L85

**Comment by nikklassen** [comment]
I ran into this problem with Cloud Run, which is designed to be restarted multiple times within 10 seconds with low QPS. Currently there does not appear to be any workaround to this (the library doesn't let me add my own labels to the resource).

**Comment by aabmass** [comment]
@nikklassen there are some other issues around Cloud Run specifically, but the plan is:

- Short term, update our resource mapping to output [`generic_task`](https://cloud.google.com/monitoring/api/resources#tag_generic_task) monitored resource.
- Long term, allow custom metrics to be written against [`cloud_run_revision`](https://cloud.google.com/monitoring/api/resources#tag_cloud_run_revision) and update the resource detection/mapping to send it

I think we should avoid the `use_unique_identifier` approach, as it is a bit of a hack and is worse for quota compared to using monitored resources.

@dashpole what do you think?

**Comment by dashpole** [comment]
That makes sense to me.  I agree we should avoid the `use_unique_identifier` if it isn't the desired end-state.   Specifically, which resource attributes do we need to detect, and what is the appropriate mapping from semantic conventions to the cloud_run_revision resource?

**Comment by nikklassen** [comment]
Correct me if I'm wrong, but it doesn't appear there's anything encoded about horizontal scaling in the `cloud_run_revision` resource, i.e. if we spin up 2 containers simultaneously in Cloud Run the `monitored_res` for each one would still look the same right?

I agree that the `use_unique_identifier` approach is pretty hacky. It also isn't perfect, in my use case I'm still getting errors shutting down the server because the periodic exporter might send a batch at a 10 second interval, but if the container shuts down a few seconds later I send another batch which is rejected. I'm not sure if the Cloud Run environment can fully avoid these errors in all situations.

**Comment by aabmass** [comment]
> Correct me if I'm wrong, but it doesn't appear there's anything encoded about horizontal scaling in the `cloud_run_revision` resource

Ah sorry you're right. I think generic_task's `task_id` label would work? Does knative/cloud run provide you with a good value for that label though?

**Comment by bkrmalick** [comment]
Are there any plans of this being fixed? Struggling with the same issue where metrics exported from concurrent goroutines are throwing that `One or more TimeSeries could not be written: One or more points were written more frequently than the maximum sampling period configured` error

**Comment by IsaacPD** [comment]
@bkrmalick If you are using custom metrics you can take the approach that I used which was just to implement something similar myself onto the label.  See https://github.com/GoogleContainerTools/skaffold/blob/main/pkg/skaffold/instrumentation/export.go#L166

**Comment by nikklassen** [comment]
If I'm reading this correctly it looks like I should put a unique ID for the Cloud Run execution into `semconv.AttributeServiceInstanceID`. That should work for me.

**Comment by dashpole** [comment]
Closing based on https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/issues/128#issuecomment-1042145981
