### ISSUE TITLE
Upgrade and release a new version for otel 0.16.0

### ISSUE THREAD

**Issue by bogdandrutu** [GoogleCloudPlatform/opentelemetry-operations-go#131]

**Comment by bogdandrutu** [comment]
@dashpole or @punya can you do a release?

**Comment by punya** [comment]
@bogdandrutu yes, we're on it.

**Comment by punya** [comment]
https://pkg.go.dev/github.com/GoogleCloudPlatform/opentelemetry-operations-go@v0.16.0
