### ISSUE TITLE
Span messages are prefixed with Span.<kind> (incorrect behaviour)

### ISSUE THREAD

**Issue by alexvanboxel** [GoogleCloudPlatform/opentelemetry-operations-go#151]
I know this is done intentionally, but it makes the Stackdriver exporter qazi unusable. It is also **not** semantically correct as it does change the meaning.

Example: If using java auto instrumentation and I want to search for a SELECT statement, I don't expect to need to search for Span.Client-SELECT ...

This is the commit that introduced the change:
https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/commit/a1393affee9a13ed21974ae1d791da1b3189f4a0

**Comment by alexvanboxel** [comment]
If the change is to surface the kind in the UI, it would be better to change the UI and not the name of the span.

**Comment by aabmass** [comment]
Related https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/issues/109

**Comment by aabmass** [comment]
@alexvanboxel we've decided to remove the whole `Span.<kind>.`, should be an easy fix

**Comment by tbarker25** [comment]
This should be fixed by #155
