### ISSUE TITLE
Unable to set DefaultTraceAttributes of the trace exporter 

### ISSUE THREAD

**Issue by filip-ph-johansson** [GoogleCloudPlatform/opentelemetry-operations-go#156]
Reviewing the code in [github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/trace@v0.18.0/cloudtrace.go](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/main/exporter/trace/cloudtrace.go) there's no constructor Option for setting the 
[DefaultTraceAttributes](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/main/exporter/trace/cloudtrace.go#L81) of the Exporter in 
```
// NewExporter creates a new Exporter thats implements trace.Exporter.
func NewExporter(opts ...Option) (*Exporter, error) {
	o := options{Context: context.Background()}
	for _, opt := range opts {
		opt(&o)
	}
	return newExporterWithOptions(&o)
}
```

**Comment by punya** [comment]
The constructor options were created in https://github.com/open-telemetry/opentelemetry-go/pull/160/commits/07c9f9ec68f47bc20930eb5e1a0e40d66c0020c9. It looks like `DefaultTraceAttributes` was left out by mistake (@ymotongpoo can confirm).

@filip-ph-johansson, would you be interested in contributing a construction option to make `DefaultTraceAttributes` configurable?

**Comment by filip-ph-johansson** [comment]
Ok, thanks for your feedback.
Sure, it should be a quick fix.

**Comment by jsuereth** [comment]
Two additions to this:

1. Are the trace attributes being added specific to just the Stackdriver exporter or are they more associated with the resource?  I'd encourage you to use: OTEL_RESOURCE_ATTRIBUTES env variable (or similar config) for this: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#general-sdk-configuration.
2. As an FYI - We're looking into pushing resource/attribute annotations-as-configuration into core OTEL capabilities.   Happy to have it on our exporter, but longer term we'd like this to just be a (consistent) feature of OTEL.

**Comment by punya** [comment]
Note that handling of OTEL_RESOURCE_ATTRIBUTES is not fully spec-compliant at the moment: https://github.com/open-telemetry/opentelemetry-go/issues/1689.

**Comment by jsuereth** [comment]
Yeah, I think we need to provide it here as an interim solution.   Ideally we can push this use case upstream over time though.

**Comment by filip-ph-johansson** [comment]
@punya Is there a reason to why the [internal attributes are built](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/main/exporter/trace/cloudtrace.go#L244) on each export? Since the default attributes are only set during the creation of the exporter we might as well build them at that time.

**Comment by punya** [comment]
@filip-ph-johansson I believe that's a holdover from an older design where DefaultTraceAttributes were mutable. Feel free to build them at creation time in your PR, if you prefer.
