### ISSUE TITLE
Replace OpenTelemetry with Google Inc as the code owner

### ISSUE THREAD

**Issue by nilebox** [GoogleCloudPlatform/opentelemetry-operations-go#16]
The License boilerplate currently states that OpenTelemetry owns the code: https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/aa81cfc9a8ab236ea98681fc7db8b3e01e6cffd6/example/trace/http/client/client.go#L1

It should probably say that the code is owned by Google, e.g. [see example](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/14a8927089a63dd59e45b52622c54ce7409836d2/monitoring/cloud-client/src/main/java/com/example/monitoring/QuickstartSample.java#L1-L3).

**Comment by lizthegrey** [comment]
You can't change this retroactively; this code contains contributions from OpenTelemetry authors who licensed this code under the OTel CLA and have not assigned copyright to Google.

**Comment by nilebox** [comment]
@lizthegrey what about the new contributions to the same files in this repo? Wouldn't the situation be opposite in that case?

If you can share the right way to handle this, that would be great.

**Comment by lizthegrey** [comment]
Correct, unless you use the OpenTelemetry CLA bot, new contributions won't be covered under _any_ CLA

so you'll need a combination of the older OTel CLA and the Google CLA bot/disclaimer.

**Comment by nilebox** [comment]
Discussed internally - we should keep OpenTelemetry header on existing files, and use Google header for new files.
