### ISSUE TITLE
Should add in release note in v0.16.0 the migration plan to use BatchSpanProcessor

### ISSUE THREAD

**Issue by eddiectc** [GoogleCloudPlatform/opentelemetry-operations-go#165]
When upgrading to v0.16.0+, we noticed ~500ms latency added to all service handing calls, and it turns out the change on #149 making the default behavior changed as each tracing call is synchronized.

Believe we should indicate that in the release note so that people are aware when upgrading from earlier version, and have instruction to use the BatchSpanProcessor if old behavior is preferred.

**Comment by punya** [comment]
Hi @eddiectc, sorry to hear this change caught you by surprise. This is already called out in the "breaking changes" section of the [v0.17.0 release notes](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/releases/tag/v0.17.0). Based on your feedback, I'll add a pointer to the BatchSpanProcessor to help users migrate.
