### ISSUE TITLE
Release new version that uses go.opentelemetry.io/otel v0.20.0

### ISSUE THREAD

**Issue by bogdandrutu** [GoogleCloudPlatform/opentelemetry-operations-go#167]

**Comment by punya** [comment]
Released https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/releases/tag/v0.20.0

**Comment by Mistic92** [comment]
Can you update readme too? I'm getting errors ```WithConfig not declared by package tracecompilerUndeclaredImportedName``` and ```Config not declared by package tracecompilerUndeclaredImportedName``` when trying to use example code.
