### ISSUE TITLE
Would like an intuitive way to set a monitored resource type

### ISSUE THREAD

**Issue by soellman** [GoogleCloudPlatform/opentelemetry-operations-go#170]
To set the monitored resource to a k8s cluster, I'm currently doing:

```
	attrs := []attribute.KeyValue{
		attribute.String("cloud.provider", mexporter.CloudProviderGCP),
		attribute.String("cloud.zone", zone),
		attribute.String("k8s.cluster.name", cluster),
	}
```
and then feeding `attrs` to a WithResource controller option.

Am I missing some mechanism to auto-detect these options?

**Comment by punya** [comment]
You can find the detectors at https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/detectors/gcp.

**Comment by soellman** [comment]
Thanks, that is useful.

However, I think it'd still be nice to have a specific API to set a monitored resource (or default to what the detector may return).

Example: I am writing a process that will run in a k8s cluster, but would export metrics under the k8s_node or k8s_cluster resource types. If I use the detector, I'd still need to manually disable certain attributes in order to massage the tag matching here:
https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/main/exporter/metric/metric.go#L341

**Comment by damemi** [comment]
Closing as not planned, workaround exists
