### ISSUE TITLE
Potential memory leak in metric exporter

### ISSUE THREAD

**Issue by ryanlaycock** [GoogleCloudPlatform/opentelemetry-operations-go#174]
We've recently added some `NewInt64UpDownCounter()`s to a service running in GKE. After about 36 hours the pods running this new code OOM crashed. The service typically uses ~150MiB consistently, but the version with this library in hit the limit of 500MiB within the 36 hours, and the rate of memory usage tended to correlate with the addition to the counters.

After digging I realised we have 2 counters, one that only ever increases, and one that increases and decreases. Would using the `UpDownCounter` for the one that only ever increases be a potential cause for the memory leak? 

I notice in the [go docs for the otel library](https://pkg.go.dev/go.opentelemetry.io/otel/api/metric) that the Counter is _monotonic_, but the `UpDownCounter` is not. What impact does this have on the underlying memory usage in the OS, and is this expected behaviour of the library? If so I think making this clear in the documentation would help avoid future issues.

**Comment by jsuereth** [comment]
I'm not sure on the impact of `Counter` vs. `UpDownCounter` in the go library, that's a better question for http://github.com/opentelemetry/opentelemetry-go.

As far as the OOM though, that could be related to this project.   The metrics component is not considered "stable" yet.   Is there any other information you have from the crash you could send us to investigate this?

Thanks!

**Comment by punya** [comment]
@ryanlaycock just checking in - are you still experiencing the OOM? We're ver interested in figuring out if this library is related in any way, so please share any information you can from the crash.

**Comment by ryanlaycock** [comment]
Apologies for not replying @punya @jsuereth, we finally got to the bottom of this issue and it wasn't related to this library - sorry for any concern! I'll close this now :)
