### ISSUE TITLE
Releasing new tag

### ISSUE THREAD

**Issue by 0xc0d** [GoogleCloudPlatform/opentelemetry-operations-go#175]
Since the latest otel-go version has been merged to the main branch. Is there anything that needs to be done before releasing a new tag?

**Comment by icco** [comment]
@punya or others, do you know?

**Comment by jsuereth** [comment]
Yeah, we're working to finish some missing features in the Trace exporter (e.g. Links are not exported).  That combined with the full integration tests being delivered by #177 and then this should be ready to release.

**Comment by 0xc0d** [comment]
Since we managed to merge link and span kind features, Is there anything left now!? Shall release a new tag?

**Comment by punya** [comment]
@0xc0d sorry this has taken a few days. We're still working on the integration tests (and some small bugs that they uncovered!). Do you have a specific need for a release? We might be able to tag an RC for you to depend on.

**Comment by 0xc0d** [comment]
@punya,for now we are relying on commit hash tagging on our side. Is there anything I can pick? I guess I can check the e2e test PR.
