### ISSUE TITLE
Unexport public variables and functions prior to 1.0

### ISSUE THREAD

**Issue by dashpole** [GoogleCloudPlatform/opentelemetry-operations-go#190]
There are a few spots where we export things unneccessarily:
* A number of constants should use otel's semantic conventions, and should at least not be exported: https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/main/exporter/trace/trace_proto.go#L48
* It is not possible to even set [Location](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/552dfa270c46b4bf6b1763281e824c6cc23ef15f/exporter/trace/cloudtrace.go#L61), and it doesn't appear to be used anywhere either.
* It is not possible to set [BatchSpanProcessorOptions](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/552dfa270c46b4bf6b1763281e824c6cc23ef15f/exporter/trace/cloudtrace.go#L76).  It also should be set as part of TracerProviderOptions, rather than the exporter options.

**Comment by punya** [comment]
@dashpole can this be closed now?

**Comment by dashpole** [comment]
Yes.  Closed
