### ISSUE TITLE
Resource Support for trace exporter.

### ISSUE THREAD

**Issue by rghetia** [GoogleCloudPlatform/opentelemetry-operations-go#20]
Convert Otel Resources to span attributes. Similar to [jaeger exporter](https://github.com/open-telemetry/opentelemetry-go/blob/485cbd4e6a4a1ad6f396674e1b36c080cea522e7/exporters/trace/jaeger/jaeger.go#L211-L217) converts to tags.

**Comment by yegle** [comment]
This issue is still referenced in `example/metric/example.go` though.
