### ISSUE TITLE
Add support for Cloud Monitoring Distributions in the metrics exporter

### ISSUE THREAD

**Issue by ronilichtman** [GoogleCloudPlatform/opentelemetry-operations-go#206]
The current implementation for `ValueRecorderInstrumentKind` is `lastvalue`. This prevents clients from having an effective way to chart latency metrics.

By populating the RPC request as described in https://cloud.google.com/monitoring/api/ref_v3/rest/v3/TypedValue#Distribution, it should be possible to implement these distribution metrics.

**Comment by aabmass** [comment]
This last value behavior has been changed to histogram in the OTel metrics specification, but the Go SDK hasn't implemented it yet. This will probably take a while, but we will definitely send distribution metrics once it is ready.

**Comment by dashpole** [comment]
The spec-compliant go SDK is tracked in https://github.com/orgs/open-telemetry/projects/22.  Once that is done, we will update this exporter--including supporting distributions.
