### ISSUE TITLE
opentelemetry-operations-go/exporter/trace rpc error: code = Unavailable

### ISSUE THREAD

**Issue by eqinox76** [GoogleCloudPlatform/opentelemetry-operations-go#208]
Hey all,

our monitoring sometimes shows the following error message from the traces exporter:

```
rpc error: code = Unavailable desc = The service is currently unavailable.

stack:
/home/go/pkg/mod/go.opentelemetry.io/otel@v1.0.0/handler.go:106                                   Handle
/home/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.0.0/trace/batch_span_processor.go:248            (*batchSpanProcessor).processQueue
/home/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.0.0/trace/batch_span_processor.go:111            NewBatchSpanProcessor.func1
/opt/go/1.16.3/x64/src/runtime/asm_amd64.s:1371                                                   goexit
```

We are using the following library versions:
```
	go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc v0.24.0
	go.opentelemetry.io/otel v1.0.0
	go.opentelemetry.io/otel/exporters/stdout/stdouttrace v1.0.0
	go.opentelemetry.io/otel/sdk v1.0.0
	go.opentelemetry.io/otel/trace v1.0.0
	github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/trace v1.0.0-RC2
```

I think the error is common among grpc systems when something is restarting or connections are lost. Maybe providing a retry option like [grpc_retry](https://github.com/grpc-ecosystem/go-grpc-middleware) would help to reduce data loss and the occurrence of such low level alerts.

Regards,
Carsten

**Comment by damemi** [comment]
It looks like the cloud trace client has [retry logic built in by default](https://github.com/googleapis/google-cloud-go/blob/trace/v1.2.0/trace/apiv2/trace_client.go#L62). I'm wondering if I followed that correctly, or if maybe something in the batch processor is dropping that retry handling?

**Comment by dashpole** [comment]
Can we test it with our mock cloud trace implementation?

**Comment by damemi** [comment]
Re-reading it, I think that retry logic is only on by default for `CreateSpans`, but our exporter uses `BatchWriteSpans`. Still need to test this, but adding a note for when I can get to it

**Comment by damemi** [comment]
Opened a PR to add this in https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/550, but going to double check with cloud trace folks first to see if there's a specific reason that `BatchWriteSpans` doesn't retry by default like `CreateSpan` before merging it

**Comment by damemi** [comment]
We ended up changing the underlying client defaults after opening https://github.com/googleapis/google-cloud-go/issues/7184. Those changes should get copied from google internal to Github soon, and the clients will be regenerated.

At that point, we'll need to bump our dependencies to pull in the new defaults but otherwise shouldn't require any code changes for this feature. We might be able to use the tests I started to add in https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/550 though.

However with this we will want to remove our default enabled `retry_on_failure` collector exporter helper, since it's redundant.

**Comment by damemi** [comment]
To update this: batch retry is now enabled by default at head in the cloud trace libraries: https://github.com/googleapis/google-cloud-go/blob/19e9d033c263e889d32b74c4c853c440ce136d68/trace/apiv2/trace_client.go#L64-L75

Once a new trace client release is tagged, I'll update #550 to try bumping that dependency here and add tests to verify

**Comment by cpheps** [comment]
@damemi @dashpole I see this retry is now removed as of OTel v0.84.0. I had a question about using the OTel persistent queue. I believe when using the OTel retry an item doesn't leave the queue until it successfully sends. So if it fails and the system shuts down the persistent queue will keep it on disk and retry.

Using the the google-cloud retry does this behavior change? If the retry fails does the item stay in the OTel sending queue or is it removed and then is discarded by the google-cloud library if it fails?

This is probably and edge case but if a collector has a persistent queue and is shut down while things are retrying are they now lost where before with the OTel retry they would be persisted on disk?

**Comment by dashpole** [comment]
> I believe when using the OTel retry an item doesn't leave the queue until it successfully sends.

That doesn't seem like the right behavior if retry is disabled.  If you are able to reproduce it, can you open a separate issue?

**Comment by cpheps** [comment]
> That doesn't seem like the right behavior if retry is disabled. If you are able to reproduce it, can you open a separate issue?

Yeah let me double check. I may be missing part of how the exporter helper works with retry and sending queue.
