### ISSUE TITLE
Add support for the k8s_service monitored resource

### ISSUE THREAD

**Issue by ronilichtman** [GoogleCloudPlatform/opentelemetry-operations-go#219]
See details on the `k8s_service` monitored resource here: https://cloud.google.com/monitoring/api/resources#tag_k8s_service.

**Comment by aabmass** [comment]
It's not possible to write custom metrics against `k8s_service`, see here: https://cloud.google.com/monitoring/custom-metrics/creating-metrics#custom-metric-resources.
