### ISSUE TITLE
Detector's region does not match the metric API's region format

### ISSUE THREAD

**Issue by nikklassen** [GoogleCloudPlatform/opentelemetry-operations-go#227]
I was trying to use the GCP detector from open-telemetry/opentelemetry-go-contrib and I started getting errors bac

```
rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: Unrecognized region or location.: timeSeries[0-8]
```

When I dug into it I can see that the detector uses the metadata service, which returns the region in the format
`projects/<project ID>/regions/<region ID>` https://cloud.google.com/run/docs/reference/container-contract (which is a rather unusual format, but whatever)

Unsurprisingly, this is not what the `generic_task` (which is what a Cloud Run environment gets mapped to) MonitoredResource expects https://cloud.google.com/monitoring/api/resources#tag_generic_task

It seems like the detector should parse out the region from the metadata server's response, and then set just the resource part of the string as the attribute

**Comment by punya** [comment]
Thanks for flagging, this should be fixed. Would you have interest in contributing a fix?

**Comment by dashpole** [comment]
Fixed by https://github.com/open-telemetry/opentelemetry-go-contrib/pull/1546
