### ISSUE TITLE
Add Readme.md for examples

### ISSUE THREAD

**Issue by rghetia** [GoogleCloudPlatform/opentelemetry-operations-go#23]
Create single readme or one for each example in example directory.
Readme should contain
- Brief description about the example.
- how to run
- Expected output.

**Comment by ymotongpoo** [comment]
README.md for the exporter example was added. Need one for Trace exporter.

**Comment by james-bebbington** [comment]
We should include documentation for how to use multiple providers, see https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/76#issuecomment-667746838

**Comment by punya** [comment]
> We should include documentation for how to use multiple providers, see [#76 (comment)](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/76#issuecomment-667746838)

I decided to document usage of multiple providers in a Go-style example func, rather than the README. It'll ensure the code keep compiling (samples in markdown files inevitably get outdated).
