### ISSUE TITLE
Send CreateMetricDescriptorRequest asynchronously

### ISSUE THREAD

**Issue by ymotongpoo** [GoogleCloudPlatform/opentelemetry-operations-go#26]
Currently [the process to call CreateMetricDescriptor is synchronous](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/bc5120a296ef9d742af67432b5b0b6f57857059f/exporter/metric/metric.go#L170-L184) and should block if the number of MetricDescriptors is large. (Note: calling CreateMetricDescriptor to existing MD is allowed, so not checking existing MD in Cloud Monitoring itself is fine.)

It should launch a new goroutine when the new MD is found and call the request asynchronously in the goroutine.

**Comment by ymotongpoo** [comment]
Note: If a record has metadata of MontoringResource A, and there are records with A in the `cps.ForEach()` loop, we need to make sure that MR A is registered before any of TimeSeries with A is submitted.

**Comment by james-bebbington** [comment]
> Note: If a record has metadata of MontoringResource A, and there are records with A in the `cps.ForEach()` loop, we need to make sure that MR A is registered before any of TimeSeries with A is submitted.

I think you meant MetricDescriptor rather than MonitoringResource here?

---

To make sure I understood this correctly, you're saying that instead of:
```
for md in uncachedMetricDescriptors:
  createMetricDescriptor(md)

create timeseries ...
```

We want:
```
for md in uncachedMetricDescriptors:
  async createMetricDescriptor(md)

block until descriptors created
create timeseries ...
```

If that's correct, do we want to (or already) do anything similar for parallelising creating timeseries?

**Comment by ymotongpoo** [comment]
@james-bebbington yes, you are right. I meant "MetricDescriptor that corresponds to MetricResource A should be registered in advance." And your pseudo snippet is exactly what I meant.

I wasn't sure how often we need such a process because we usually have MD initialization when we have such metrics for the first time, and I do not have the evidence to reinforce the need of this feature request.

**Comment by punya** [comment]
@jsuereth I know you were thinking about whether the operations repos should create MetricDescriptors at all, or just let the backend infer them. Could you weigh in here?

**Comment by jsuereth** [comment]
Sorry for delay.  Yes I think longer term we should avoid sending metric descriptors.  In the short term, we need them for feature parity and to make sure OTel configuration DOES make it into GCM.

Regarding this issue I think the following is true:

- We should stick w/ synchronous MD send as the default.   
- I think we would allow an implementation for MD sending that is parallel and a configurable option, especially if this becomes a large problem and parallel RPCs (vs. bundling) leads to higher throughput (I'd need a benchmark showing me this first)
- Longer term, we hope to bridge some gaps and remove the need to send MDs from OTEL at all.   However that's far enough away I think a workaround is in order, assuming someone can demonstrate the issue and the speedup in practice.

**Comment by dashpole** [comment]
Fixed by https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/247
