### ISSUE TITLE
Configure MonitoringResource for TimeSeries

### ISSUE THREAD

**Issue by ymotongpoo** [GoogleCloudPlatform/opentelemetry-operations-go#29]
Currently the second argument of [`Exporter.Export()`](https://pkg.go.dev/go.opentelemetry.io/otel/sdk/export/metric@v0.5.0?tab=doc#Exporter) is meant for the common resource among all records stored via a meter, and the resource is the counterpart of MonitoredResource in TimeSeries.

In OpenCensus, [the interface for MonitoredResource is defined apart from the protobuf and controlled separately](https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/tree/master/monitoredresource). Similarly to OpenCensus, OpenTelemetry exporter should have the extra care for MonitoredResource.

For now, it just returns ["global"](https://cloud.google.com/monitoring/api/resources#tag_global) resource. ([hard coded](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/master/exporter/metric/metric.go#L283-L296))

**Comment by ymotongpoo** [comment]
@dashpole could you confirm if this is still the case or not?

**Comment by ymotongpoo** [comment]
I confirmed that metrics attributes work perfectly in [this code](https://github.com/ymotongpoo/google-cloud-samples/blob/main/cloud-run-constant-metric/main.go#L111-L115), so when switching to `generic_task`, I think we need to have it move all labels that are not defined for the `monitored_resource` as well. WDYT?

**Comment by dashpole** [comment]
Yeah, similar to the collector exporter's [resource_filters](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/main/exporter/collector/config.go#L95) option, it would be nice to be able to elevate additional resource attributes to metric labels.  I don't think we should do that for all additional labels, though, as detectors (e.g. for language or env, etc) often generate a very large number of attributes.  By default, we shouldn't add additional labels

**Comment by damemi** [comment]
We support all the monitored resources listed above except dataflow_job. We can open a separate issue to track support for dataflow if it's requested.
