### ISSUE TITLE
exporter/metric: multiple problems with example

### ISSUE THREAD

**Issue by jba** [GoogleCloudPlatform/opentelemetry-operations-go#291]
I'm trying to use the exporter/metric module at v1.0.0-RC1. I copied the program in the README into its own module and tried to run it. Repeated here for convenience:
```
package main

import (
    "go.opentelemetry.io/otel/metric"
    "go.opentelemetry.io/otel/label"
    "go.opentelemetry.io/otel/sdk/metric/controller/basic"
    "go.opentelemetry.io/otel/sdk/resource"

    mexporter "github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/metric"
)

func main() {
    // Initialize exporter option.
    opts := []mexporter.Option{}
    popts:= []basic.Option{}

    // Create exporter (collector embedded with the exporter).
    pusher, err := mexporter.InstallNewPipeline(opts, popts...)
    if err != nil {
        log.Fatalf("mexporter.InstallNewPipeline: %v", err)
    }
    ctx := context.Background()
    defer pusher.Stop(ctx)

    // Start meter
    meter := pusher.Provider().Meter("cloudmonitoring/example")

    counter := metric.Must(meter).NewInt64Counter("counter-foo")
    labels := []label.KeyValue{
        label.Key("key").String("value"),
    }
    counter.Add(ctx, 123, labels...)
}
```
Running `go get github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/metric@v1.0.0-RC1` succeeded.

Trying to then run the program, I was asked to `go get go.opentelemetry.io/otel/label`; that failed with
```
go: module go.opentelemetry.io/otel@upgrade found (v1.3.0), but does not contain package go.opentelemetry.io/otel/label
```
I commented out the lines referring to labels and tried again. This time I got:
```
pusher.Provider undefined (type *basic.Controller has no field or method Provider)
```

**Comment by dashpole** [comment]
It looks like v1.0.0-RC1 of that module was tagged accidentally: At https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/tree/d9f756207d97f78454936537367ba569c420c28b, which should have been v0.22.0 instead

The most recently released version of exporter/metric is exporter/metric/v0.24.0, which is compatible with upstream otel's v0.24.0 metric release.

The modules are still experimental, so it is expected that versions of otel and the exporter need to match.  We try to keep up with changes upstream, but are often behind a release or two.

> I'm also noticing that this module seems to use go.opentelemetry.io/otel at v1.0.0-RC1, but that module is already at v1.3.0.

The most recent release requires a minimum of `v1.0.1` of the stable upstream modules, which is compatible with v1.3.0 if you would like to use the most recent upstream release.

**Comment by jba** [comment]
> The most recent release ...

Do you mean at main? I was able to get that to work as far as modules are concerned.

The example in the README is still broken because it uses labels and calls the non-existent Provider method.

I tried

**Comment by dashpole** [comment]
> Do you mean at main?

I mean:
```sh
go get go.opentelemetry.io/otel/metric@v0.24.0
go get go.opentelemetry.io/otel/sdk/metric@v0.24.0
go get github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/metric@v0.24.0
```

**Comment by dashpole** [comment]
I believe this should be addressed through the retraction of incorrect releases.  Feed free to reopen if you still have issues
