### ISSUE TITLE
Add support for concurrent processes in metric exporter

### ISSUE THREAD

**Issue by ymotongpoo** [GoogleCloudPlatform/opentelemetry-operations-go#30]
Current implementation of metric exporter doesn't consider the concurrent processes well and it is not as efficient as expected and may cause data race. The parts to check concurrency safety are:

* MetricDescriptor caching
* Batch conversion from Record to TimeSeries

**Comment by psx95** [comment]
Currently not our top priority since there are no reported bugs, but would be happy to review a PR to address this issue.

**Comment by aabmass** [comment]
Going to close this out. The metric exporter has changed a lot in the last 3 years. Please re-open if there is a specific issue
