### ISSUE TITLE
exporter/collector: support logs

### ISSUE THREAD

**Issue by odsod** [GoogleCloudPlatform/opentelemetry-operations-go#326]
If the collector were able to forward logs to Cloud Logging, it would greatly improve the logging story in e.g. IoT environments where the `filelogreceiver` is used.

**Comment by dashpole** [comment]
The collector exporter now supports logs.  The entrypoint in this repo is https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/main/exporter/collector/logs.go#L125.

Thanks @damemi!
