### ISSUE TITLE
usage of deprecated `Type` func

### ISSUE THREAD

**Issue by codeboten** [GoogleCloudPlatform/opentelemetry-operations-go#329]
The collector/metric.go still uses the deprecated `Type` functions, see https://github.com/open-telemetry/opentelemetry-collector/blob/main/CHANGELOG.md#-deprecations- for deprecation notice. These have been removed in the version of the collector in [main](https://github.com/open-telemetry/opentelemetry-collector/blob/main/CHANGELOG.md#-breaking-changes-).

Observed while trying to update the collector core repository in the contrib repo: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/8334

```
# github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/collector
../../go/pkg/mod/github.com/!google!cloud!platform/opentelemetry-operations-go/exporter/collector@v0.26.0/metricsexporter.go:760:10: point.Type undefined (type "go.opentelemetry.io/collector/model/internal/pdata".NumberDataPoint has no field or method Type)
../../go/pkg/mod/github.com/!google!cloud!platform/opentelemetry-operations-go/exporter/collector@v0.26.0/metricsexporter.go:984:59: m.Gauge().DataPoints().At(0).Type undefined (type "go.opentelemetry.io/collector/model/internal/pdata".NumberDataPoint has no field or method Type)
../../go/pkg/mod/github.com/!google!cloud!platform/opentelemetry-operations-go/exporter/collector@v0.26.0/metricsexporter.go:996:57: m.Sum().DataPoints().At(0).Type undefined (type "go.opentelemetry.io/collector/model/internal/pdata".NumberDataPoint has no field or method Type)
```

This is the code that needs to be updated: 
https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/2cab245a6ebca077e6badb074ac5061c0ee67e69/exporter/collector/metrics.go#L742

**Comment by dashpole** [comment]
I'm working on it :) https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/328
