### ISSUE TITLE
Update to v0.6.0 compat

### ISSUE THREAD

**Issue by ymotongpoo** [GoogleCloudPlatform/opentelemetry-operations-go#33]
Update metric and trace exporter to opentelemetry-go v0.6.0 compat

- [x] Metric
- [ ] Trace

**Comment by james-bebbington** [comment]
@ymotongpoo looks like both exporters are updated - can this one be closed now?

**Comment by ymotongpoo** [comment]
@james-bebbington yes it does and we can close this issue now.
