### ISSUE TITLE
Add span attributes for library name and version

### ISSUE THREAD

**Issue by dashpole** [GoogleCloudPlatform/opentelemetry-operations-go#332]
Based on our exporter spec, they should be added as `otel.instrumentation_library.name` and `otel.instrumentation_library.version`.   Although, I believe that plan should be altered by https://github.com/open-telemetry/opentelemetry-specification/pull/2276, which changed them to suggest `otel.scope.name` and `otel.scope.version`.

**Comment by aabmass** [comment]
For the collector metrics exporter, we are doing `instrumentation_source` and `instrumentation_version` (for telemetry attribution). Should we do the same for traces?

**Comment by dashpole** [comment]
This is the relevant OTel spec: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/non-otlp.md#instrumentationscope

**Comment by dashpole** [comment]
Ah, I forgot, we should use `instrumentation_source` and `instrumentation_version` to match metrics.
