### ISSUE TITLE
Allow Unix epoch (1970) as default starttimestamp

### ISSUE THREAD

**Issue by danelowe** [GoogleCloudPlatform/opentelemetry-operations-go#335]
It appears as though the `opentelemetry-collector` might be adding `1970-01-01` as the default value for StartTimestamp on TimeSeries DataPoints. 

https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/b068af9a94200ed9c49d58f16817ea6d3066e6e6/exporter/collector/metrics.go#L740

Here the code expects it to be `0001-01-01`, resulting in data not being sent to Google Cloud. 

Also `opentelemetry-collector` stores timestamps as unsigned integers from 1970, so can't set the StartTimestamp to `0001-01-01` without counting on integer overflows.

https://github.com/open-telemetry/opentelemetry-collector/issues/5102

**Comment by dashpole** [comment]
This was fixed in https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/336
