### ISSUE TITLE
metric - counter example doesn't work properly

### ISSUE THREAD

**Issue by kanekv** [GoogleCloudPlatform/opentelemetry-operations-go#37]
I have tried simple Counter example, it doesn't show up properly in metrics dashboard.
Both rate/delta aligners show constantly growing counter instead of rate.
I had a simple loop, incrementing counter every 100ms and it supposed to show rate of 10requests/sec, instead it seems to show something constantly growing (not a raw value though as well).

**Comment by nilebox** [comment]
@ymotongpoo have you tested this with metrics dashboard?

**Comment by ymotongpoo** [comment]
@nilebox I checked that the exporter sends some data to the dashboard but it may have some problems on MetricType checking part. It requires some investigations.

**Comment by kanekv** [comment]
@ymotongpoo did you have a chance to test it? I can help with repro if needed.

**Comment by ymotongpoo** [comment]
@kanekv if you have the code to reproduce the situation, it's really helpful.
