### ISSUE TITLE
Only attach instrumentation scope when it is non-empty

### ISSUE THREAD

**Issue by dashpole** [GoogleCloudPlatform/opentelemetry-operations-go#377]
Some receivers don't set instrumentation scope name/version, which produces telemetry with a bunch of empty labels.  It might be a better UX to omit it in that case, even if the exporter has instrumentation labels enabled.  The same point also goes for service labels.

**Comment by aabmass** [comment]
This seems reasonable to me. For a given metric descriptor though, if any writer **ever** had instrumentation scope or service labels, they will appear in all time series for that descriptor. IIRC GCM will happily use an empty string if the labels are missing, but would be good to double check.

**Comment by damemi** [comment]
Looking into this
