### ISSUE TITLE
Update exporter/trace version to 0.2.0

### ISSUE THREAD

**Issue by rosstimothy** [GoogleCloudPlatform/opentelemetry-operations-go#38]
Can you create a 0.2.0 tag for exporter/trace as well?

**Comment by EronWright** [comment]
Quick workaround: fork this library, checkout the `v0.2.0` release, and add the missing tag. 
```shell
git clone https://github.com/YOUR_FORK/opentelemetry-operations-go.git
cd opentelemetry-operations-go
git checkout ec6b73c1970b009e48adce4d59d6dbbc97ba736e
git tag -a exporter/trace/v0.2.0
git push origin exporter/trace/v0.2.0
```

Then use your fork in your application's `go.mod`:
```
replace (
	go.opentelemetry.io/otel => go.opentelemetry.io/otel v0.6.0
	github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/trace => github.com/YOUR_FORK/opentelemetry-operations-go/exporter/trace v0.2.0
)
```

**Comment by ymotongpoo** [comment]
@nilebox @rghetia should we consider putting tags independently for trace and metric?

**Comment by nilebox** [comment]
I'd rather use the shared version for both traces and metrics, it's easier to follow.

**Comment by nilebox** [comment]
I have published tags for all modules:
- exporter/trace/v0.2.0
- exporter/metric/v0.2.0
- example/trace/http/v0.2.0
- example/metric/v0.2.0

We should probably write a script to automate this.

**Comment by rghetia** [comment]
> I have published tags for all modules:
> 
> * exporter/trace/v0.2.0
> * exporter/metric/v0.2.0
> * example/trace/http/v0.2.0
> * example/metric/v0.2.0
> 
> We should probably write a script to automate this.

There are scripts in otel-go that can be copied.

1. [pre_release.sh](https://github.com/open-telemetry/opentelemetry-go/blob/master/pre_release.sh)
2. [tag.sh](https://github.com/open-telemetry/opentelemetry-go/blob/master/tag.sh)
3. [verify_example.sh](https://github.com/open-telemetry/opentelemetry-go/blob/master/verify_examples.sh)
