### ISSUE TITLE
googlemanagedprometheus `Duplicate TimeSeries encountered`

### ISSUE THREAD

**Issue by CatherineF-dev** [GoogleCloudPlatform/opentelemetry-operations-go#420]
Thanks for the work!
 https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/tree/main/exporter/collector/googlemanagedprometheus.

Used googlemanagedprometheus exporter inside open-telemetry, and found error message 
`written per TimeSeries per request.; Field timeSeries[190] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.; Field timeSeries[111] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.\nerror details: name = Unknown  desc = total_point_count:200  errors:{status:{code:3}  point_count:200}", "interval": "19.604271258s"}`.

Not sure whether it's related to empty job and instance.

**Comment by CatherineF-dev** [comment]
cc @dashpole

**Comment by dashpole** [comment]
Just make sure for non-prometheus receivers, you set `service.name` and `service.instance.id` resource attributes.

**Comment by CatherineF-dev** [comment]
Thanks! 

- Metrics from prometheus receiver
Verified they are exported successfully
- Metrics from non-prometheus receiver
 Will try setting `service.name` and `service.instance.id`.

**Comment by dashpole** [comment]
Feel free to reopen if you are still having problems.
