### ISSUE TITLE
Google Cloud Exporter removes attributes from OTLP log entries

### ISSUE THREAD

**Issue by jsirianni** [GoogleCloudPlatform/opentelemetry-operations-go#423]
**Issue**

When using Logging exporter and Google exporter, I noticed that the Cloud Monitoring log entry did not contain attributes despite these attributes being present in the Logging exporter's output.

Logging exporter output:

```
Jun 10 15:56:04 fedora observiq-otel-collector[499827]: 2022-06-10T15:56:04.178-0400        DEBUG        loggingexporter/logging_exporter.go:82        ResourceLog #0
Jun 10 15:56:04 fedora observiq-otel-collector[499827]: Resource SchemaURL: https://opentelemetry.io/schemas/1.6.1
Jun 10 15:56:04 fedora observiq-otel-collector[499827]: Resource labels:
Jun 10 15:56:04 fedora observiq-otel-collector[499827]:      -> host.name: STRING(fedora)
Jun 10 15:56:04 fedora observiq-otel-collector[499827]:      -> os.type: STRING(linux)
Jun 10 15:56:04 fedora observiq-otel-collector[499827]: ScopeLogs #0
Jun 10 15:56:04 fedora observiq-otel-collector[499827]: ScopeLogs SchemaURL:
Jun 10 15:56:04 fedora observiq-otel-collector[499827]: InstrumentationScope
Jun 10 15:56:04 fedora observiq-otel-collector[499827]: LogRecord #0
Jun 10 15:56:04 fedora observiq-otel-collector[499827]: ObservedTimestamp: 2022-06-10 19:56:04.076019131 +0000 UTC
Jun 10 15:56:04 fedora observiq-otel-collector[499827]: Timestamp: 1970-01-01 00:00:00 +0000 UTC
Jun 10 15:56:04 fedora observiq-otel-collector[499827]: Severity:
Jun 10 15:56:04 fedora observiq-otel-collector[499827]: Body: a test message 2
Jun 10 15:56:04 fedora observiq-otel-collector[499827]: Attributes:
Jun 10 15:56:04 fedora observiq-otel-collector[499827]:      -> log_type: STRING(file)
Jun 10 15:56:04 fedora observiq-otel-collector[499827]:      -> log.file.name: STRING(messages)
Jun 10 15:56:04 fedora observiq-otel-collector[499827]: Trace ID:
Jun 10 15:56:04 fedora observiq-otel-collector[499827]: Span ID:
Jun 10 15:56:04 fedora observiq-otel-collector[499827]: Flags: 0
```

Google Cloud Logging:

![Screenshot from 2022-06-10 15-56-33](https://user-images.githubusercontent.com/23043836/173367684-c0ef3cb1-8401-4c1d-bf21-791583d2a7b2.png)

**Expectation**

Open Telemetry [log data model](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#field-body) suggests that `body` should remain a string and parsed values should end up under `attributes`. With the Google exporter, I need to `parse_to` `body` as all resources and attributes seem to be omitted in Cloud Logging.

I have collectors running in onprem environments ingesting log data from many different sources. None of which line up with the http request that is given in the collector's example.

**Config**

My configuration looks like this, using the latest version of Open Telemetry Contrib

```yaml
receivers:
  filelog:
    include: [ ./in ]
    start_at: beginning

processors:
  resourcedetection:
    detectors: ["system"]
    system:
      hostname_sources: ["os"]

  attributes:
    actions:
      - key: gcp.log_name
        action: insert
        value: test

exporters:
  logging:
    loglevel: debug

  googlecloud:

service:
  pipelines:
    logs:
      receivers:
      - filelog
      processors:
      - resourcedetection
      - attributes  
      exporters:
      - googlecloud
      - logging
```

**Comment by damemi** [comment]
Hi @jsirianni, I think https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/424 will fix your problem. We weren't parsing the rest of the attributes to labels, which we should have been.

**Comment by jsirianni** [comment]
@damemi, will attributes be limited to `map[string]string`?

**Comment by damemi** [comment]
@jsirianni the GCP labels are limited to `<string, string>`, so attributes will be converted to that as well. Object attributes should end up as a json-encoded string value in the labels map

**Comment by jsirianni** [comment]
Thank you for jumping on this so quickly 👍
