### ISSUE TITLE
Be less prescriptive about span names

### ISSUE THREAD

**Issue by EronWright** [GoogleCloudPlatform/opentelemetry-operations-go#45]
I observe that the exporter has an opinion about span names, and I feel that it shouldn't. 

Note that `exporter/trace/trace_proto.go` computes the span display name, which makes it impossible to use short, application-specific span names as enjoyed by other Cloud Tracing applications (e.g. a method name).

Suggestion for improvement:
1. introduce a formatter in the exporter options to generate the span display name.
2. Use the existing logic as the default formatter.

**Comment by stevencl1013** [comment]
This should be resolved now, you can see this [test](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/commit/a1393affee9a13ed21974ae1d791da1b3189f4a0#diff-30183b1f2afef55ac0a5fff5bf0b340dR133) for an example of how to write and use your own formatter.

**Comment by EronWright** [comment]
Thanks @stevencl1013 it looks great!
