### ISSUE TITLE
Support for Console Exporter

### ISSUE THREAD

**Issue by avarghese-sqsp** [GoogleCloudPlatform/opentelemetry-operations-go#462]
I have been following the example in the docs to setup OTEL for Stackdriver and it works as expected when running on GCP. But during local development, it is not possible to validate if the metrics are created as expected as there is no option to provide a console exporter even though OTEL has [support](https://opentelemetry.io/docs/instrumentation/go/getting-started/#creating-a-console-exporter). Checking the source code, I was hoping to see an interface that could be used to swap out exporters based on the environment in which the code executes but this package only has structs everywhere. 

Is this on the roadmap to provide flexibility for exporters?

**Comment by dashpole** [comment]
Our exporters implement the interfaces defined by opentelemetry-go, which aren't currently designed to be environment-based.  Maybe you could add a flag or environment variable to switch to use the stdout exporter, and set the flag when you are developing locally?

**Comment by avarghese-sqsp** [comment]
So you recommend I use the interfaces from OTEL in the code and then use this package for concrete implementations?

**Comment by avarghese-sqsp** [comment]
Is `SpanExporter` the [interface](https://github.com/open-telemetry/opentelemetry-go/blob/main/sdk/trace/span_exporter.go#L21) you were referring to?

**Comment by dashpole** [comment]
Yes, that is the correct interface.  It is implemented by both the stdout exporter and the gcp trace exporter.

**Comment by avarghese-sqsp** [comment]
Perfect, I can use this interface in my code and then swap the exporter based on the environment. Thank you for the assistance!
