### ISSUE TITLE
Latency issues of HTTP requests with Stackdriver tracing v0.2.0 and otel v0.6.0

### ISSUE THREAD

**Issue by filip-ph-johansson** [GoogleCloudPlatform/opentelemetry-operations-go#47]
When running Stackdriver as an exporter for opentelemetry I'm seeing some latecy issues in HTTP requests.
In the example I'm running GET on [https://google.com](https://google.com) which normally takes 50-100ms. With Stackdriver exporter enabled the request averages between 5000-7000ms.

This is the code I'm running:
```go
package main

import (
	"context"
	"log"
	"net/http"
	"os"

	texporter "github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/trace"
	"go.opentelemetry.io/otel/api/global"
	"go.opentelemetry.io/otel/plugin/httptrace"

	sdktrace "go.opentelemetry.io/otel/sdk/trace"
)

func main() {
	projectID := os.Getenv("GCP_PROJECT_ID")
	exporter, err := texporter.NewExporter(texporter.WithProjectID(projectID))
	if err != nil {
		log.Fatalf("texporter.NewExporter: %v", err)
	}
	tp, err := sdktrace.NewProvider(sdktrace.WithSyncer(exporter))
	if err != nil {
		log.Fatal(err)
	}
	global.SetTraceProvider(tp)

	tracer := global.TraceProvider().Tracer("example.com/trace")

	ctx := context.Background()
	ctx, span := tracer.Start(ctx, "Opentelemetry HTTP GET")

	client := http.DefaultClient

	req, _ := http.NewRequest("GET", "https://google.com", nil)
	ctx, req = httptrace.W3C(ctx, req)
	httptrace.Inject(ctx, req)

	_, err = client.Do(req)
	if err != nil {
		panic(err)
	}

	span.End()
}
```

My go.mod file:
```
module foo.com

go 1.14

require (
	github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/trace v0.2.0
	go.opentelemetry.io/otel v0.6.0
)
```

Trace overview:
![image](https://user-images.githubusercontent.com/5139954/84875841-cd9dd280-b086-11ea-8e61-8c8c06024722.png)

**Comment by nilebox** [comment]
@filip-ph-johansson could you please try making multiple requests, to see if there is some issue with the initial connection / handshake?

**Comment by filip-ph-johansson** [comment]
@nilebox I get the same behaviour for multiple requests.

**Comment by stevencl1013** [comment]
@filip-ph-johansson I think that this is happening because the current implementation of the exporter exports spans using the same thread as the application. After [this PR](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/39), spans will be uploaded asynchronously, and I expect that the latency will go back to normal. 

Once these changes are made, you may need to update your code to sleep for a few seconds at the end so that the worker thread(s) can finish uploading the spans in the background before the program ends.

**Comment by james-bebbington** [comment]
> @filip-ph-johansson I think that this is happening because the current implementation of the exporter exports spans using the same thread as the application. After [this PR](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/39), spans will be uploaded asynchronously, and I expect that the latency will go back to normal. 

👍

> Once these changes are made, you may need to update your code to sleep for a few seconds at the end so that the worker thread(s) can finish uploading the spans in the background before the program ends.

Maybe we should consider adding a flush method similar to https://github.com/open-telemetry/opentelemetry-go/blob/1301b6f3e4b5a8c903e86dbc030e0527d01f807f/example/jaeger/main.go

**Comment by thecodejunkie** [comment]
@stevencl1013 great! Any rough guestimete when that will hit master? We would love that to happen 😄 

@james-bebbington It would be great if all exporters have a unified signature to make them interchangeable. We sometimes use the Jaeger exporter and would like to add Stackdriver into the mix, so we've had to create our own abstraction layer so they're both expose the same signature to our services.. so for Stackdriver we pretty much just return a noop-flush atm

**Comment by stevencl1013** [comment]
@thecodejunkie it's merged now! 

I'm currently working on a pipeline method to create the exporter and provider and return a flush similar to the Jaeger exporter.

**Comment by williambrode** [comment]
We were seeing this issue and I just updated from v.0.2.0 to latest and we no longer have the span sending slowing down our app.  Before the update there were noticeable gaps between two spans where no code in our application was running.  Turns out it was the span sending synchronously.  Thanks for the fix!
