### ISSUE TITLE
failed to export to Google Cloud Trace: rpc error: code = DeadlineExceeded desc = context deadline exceeded

### ISSUE THREAD

**Issue by wopol** [GoogleCloudPlatform/opentelemetry-operations-go#475]
I am getting this error every 1 or 2 hours. Is the default 5s timeout correct? Should we increase it? Or maybe is something wrong on my end?

I noticed that in other libraries another default Timeout is used: https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/blob/master/stackdriver.go#L292

**Comment by dashpole** [comment]
That does seem low.  Let me double-check.

**Comment by dashpole** [comment]
Java seems to use 10s: https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/blob/c27ed8fe2cde16b3bda6583fa9bc49dad8ca6446/exporters/trace/src/main/java/com/google/cloud/opentelemetry/trace/TraceConfiguration.java#L43.  We python and js clients don't appear to set a timeout.  We use 12s for the collector exporter.  12s seems like a better default to use

**Comment by wopol** [comment]
I've increased timeout by myself manually but still, I am getting the same error. Definitely not so often but still

**Comment by dashpole** [comment]
Thats interesting... You are welcome to increase it further.  You might also want to try decreasing the batch size in the batcher: https://github.com/open-telemetry/opentelemetry-go/blob/1f5b159161e0ff54df4677284fa7d6718dc9186d/sdk/trace/batch_span_processor.go#L43
