### ISSUE TITLE
Please review usages in non test code of the Slices (Buckets/Boundaries/Negative/Positive) 

### ISSUE THREAD

**Issue by bogdandrutu** [GoogleCloudPlatform/opentelemetry-operations-go#479]
Please take a look at the new APIs for primitive slices and provide us feedback, if with the current API you can avoid unnecessary allocations (keep in mind that every time you call `AsRaw` or `FromRaw` the slices are copied so you cause unnecessary allocations).

**Comment by dashpole** [comment]
Non-test usages of FromRaw/AsRaw to review:

* [exporter/collector/internal/normalization/standard_normalizer.go](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/main/exporter/collector/internal/normalization/standard_normalizer.go)
* [exporter/collector/logs.go](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/main/exporter/collector/logs.go)

**Comment by dashpole** [comment]
I think the new APIs will work well for us.  They follow familiar patterns for pdata (EnsureCapacity, At(i), etc)

**Comment by bogdandrutu** [comment]
One mistake that I see, and probably we need to fix. EnsureCapacity does not ensure the len as well. So this usage is incorrect:

```golang
	newBuckets := newPoint.BucketCounts()
	newBuckets.EnsureCapacity(aBuckets.Len()). // Here only the cap is ensured, not the len
	for i := 0; i < aBuckets.Len(); i++ {
		newBuckets.SetAt(i, aBuckets.At(i)-bBuckets.At(i))
	}
```

I see some options to solve this, ideas are welcome.

**Comment by dashpole** [comment]
Ah, OK

**Comment by dashpole** [comment]
Append is good as an API.

**Comment by bogdandrutu** [comment]
Ideas on how to design/document the API to tell people to avoid that are welcomed :D

**Comment by dashpole** [comment]
I don't know if we should make a big deal out of this.  I would have caught it immediately if I was able to compile my code (`EnsureCapacity` doesn't exist yet in the version this repo is on).  I like the consistency with other slice functions in pdata.

(probably bad) ideas anyways:

* Make SetAt append empty items if `i` is outside len
* Add an AppendEmpty() to slices that doesn't return anything, but increases the length by 1.  That way I mostly use the same pattern everywhere?
* Document "slice equivalent" of pdata functions (e.g. append() for Append(), make([]foo, 0, 5) for EnsureCapacity, foo[i] = bar for SetAt)

**Comment by dashpole** [comment]
(but TBH I didn't read the function. comments when I wrote the code)
