### ISSUE TITLE
Version update affects expected fixtures

### ISSUE THREAD

**Issue by damemi** [GoogleCloudPlatform/opentelemetry-operations-go#485]
After updating the version in `release.go`, and running `make prepare-release`, the fixure-based unit test failed.  Then, I ran `make fixtures`, and committed the results.

_Originally posted by @dashpole in https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/issues/464#issuecomment-1201335826_

**Comment by aabmass** [comment]
Specifically the user agent string changes because the upstream OTel Go version has changed. Discussed in triage and we are thinking this is expected and we should just commit the changed fixtures in these cases. That way it serves as a changelog of expected changes too.
