### ISSUE TITLE
Allow configuring the GMP prefix

### ISSUE THREAD

**Issue by dashpole** [GoogleCloudPlatform/opentelemetry-operations-go#504]
There are first-party use-cases in which we want GMP-style metrics outside of the prometheus.googleapis.com domain

**Comment by aabmass** [comment]
Not a high priority right now

**Comment by damemi** [comment]
Self-assigning this, it's still not a top priority at the moment but it's on our radar. If there are any more details about teams that are looking for this we could bump the priority and get to this sooner

**Comment by dashpole** [comment]
Fixed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/15232
