### ISSUE TITLE
Cloud Exporter Error Messages Do Not Include Metric Names

### ISSUE THREAD

**Issue by Dylan-M** [GoogleCloudPlatform/opentelemetry-operations-go#507]
Several (all?) metric errors from the exporter do not include metric names. This is related to issue #443 - in that this is a different error message about time series, but still does not include the name. It does include a reference to it, but it is not human readable, or any way to know what metric these entries map to.

`{"level":"error","ts":"2022-10-03T15:15:07.495-0400","caller":"exporterhelper/queued_retry.go:361","msg":"Exporting failed. Try enabling retry_on_failure config option to retry on retryable errors","kind":"exporter","data_type":"metrics","name":"googlecloud/googlecloud__GCP","error":"failed to export time series to GCM: rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: Field timeSeries[15].points[0].distributionValue had an invalid value: Distribution bucket_counts(2) has a negative count.; Field timeSeries[66].points[0].distributionValue had an invalid value: Distribution bucket_counts(1) has a negative count.\nerror details: name = Unknown  desc = total_point_count:73 success_point_count:71 errors:{status:{code:3} point_count:2}","stacktrace":"go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send\n\t/home/runner/go/pkg/mod/go.opentelemetry.io/collector@v0.61.0/exporter/exporterhelper/queued_retry.go:361\ngo.opentelemetry.io/collector/exporter/exporterhelper.(*metricsSenderWithObservability).send\n\t/home/runner/go/pkg/mod/go.opentelemetry.io/collector@v0.61.0/exporter/exporterhelper/metrics.go:133\ngo.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1\n\t/home/runner/go/pkg/mod/go.opentelemetry.io/collector@v0.61.0/exporter/exporterhelper/queued_retry.go:206\ngo.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func1\n\t/home/runner/go/pkg/mod/go.opentelemetry.io/collector@v0.61.0/exporter/exporterhelper/internal/bounded_memory_queue.go:61"}`

**Comment by dashpole** [comment]
Thanks for reporting this.  This looks like the same issue, albeit with a different message.  Do you mind if I close this as a duplicate, or did you want help debugging the issue?
