### ISSUE TITLE
GCE to also get hostname

### ISSUE THREAD

**Issue by nhamlh** [GoogleCloudPlatform/opentelemetry-operations-go#511]
For our usecase, we're running on GKE and would love to also have hostname of GCE requested and populated to otel-collector. Currently, the HostName returns InstanceName instead of hostname: 
https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/ca90414cd9c87f4babe529bdaf7241810d7336db/detectors/gcp/gce.go#L41-L44

I just wonder if there's any reason blocking adding it? If not, I can open a PR for this.

**Comment by dashpole** [comment]
That seems reasonable to me.  Feel free to add it as GCEHostHostname or GCEHostname.  As a note, GCE attributes are not accessible on GKE if you are using workload identity (or autopilot, which uses workload identity).

**Comment by nhamlh** [comment]
@dashpole as a side note, should we deprecate `GCEHostName` and use GCEInstanceName`? IMO, it'll avoid ambiguous; however this change will break downsteam project.

**Comment by dashpole** [comment]
I just realized they changed the host name attributes recently: https://github.com/open-telemetry/opentelemetry-specification/pull/838.  It appears we can only have either the name of the host, or the hostname of the instance as a semantic convention.

I assume hostname and instance name are generally significantly different"

**Comment by nhamlh** [comment]
In this case I think they are not that much of the difference. Actually, exposing GCE hostname would leave users with a more flexible of choices: why GCE on GKE expose hostname instead of instance name, users can use `gcp` detector to get the hostname, or `system` detector to get instance name of hostname command.

In resourcedetection processor we can add a fallback from instance name to hostname, wdyt?

**Comment by nhamlh** [comment]
The system detector doesn't use GCE metadata server, it picks the hostname locally if used with `hostname_sources: ["os"]` which is actually the `instance.name` metadata. So users can choose to use system detector or gcp detector's fqdn hostname for `host.name`, that's the flexible I mentioned before.

**Comment by aabmass** [comment]
Thanks for the PR @nhamlh. We'll try to get this reviewed and merged soon

**Comment by dashpole** [comment]
I agree with mx-psi above.  I would prefer to see this added to the specification before adding it to the resource detector.

**Comment by damemi** [comment]
To summarize, we can't change the value of [`host.name` in the collector](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/bc239b5b1f7f9837700855de8e8a5d1d9104df03/processor/resourcedetectionprocessor/internal/gcp/gcp.go#L71) because that would be breaking. But, we can add 2 new gcp specific labels `gcp.instance.name` and `gcp.instance.hostname` in the resource detection processor.

The change in #515 alone won't break anything, because that's just adding the new method to the detector. For that reason, I think we could go ahead and merge #515 without any spec changes, but adding the new labels by default in the collector processor should have the spec change first. Does that sound right to everyone?

**Comment by damemi** [comment]
Opened https://github.com/open-telemetry/opentelemetry-specification/pull/3384 upstream to add `gcp.gce.instance.name` and `gcp.gce.instance.hostname`

**Comment by damemi** [comment]
With https://github.com/open-telemetry/semantic-conventions/pull/15 merged, we will be using the 2 new attributes mentioned above (once a new semconv release is published)

@nhamlh, are you still interested in working on #515 ?

**Comment by damemi** [comment]
Opened https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/669
