### ISSUE TITLE
Sum aggregation  with CumulativeTemporality shows as delta in metric explorer

### ISSUE THREAD

**Issue by ktong** [GoogleCloudPlatform/opentelemetry-operations-go#518]
The metric data `metricdata.Sum[N]{DataPoints: points, Temporality: metricdata.CumulativeTemporality}` is generated by opencensus bridge at https://github.com/open-telemetry/opentelemetry-go/blob/main/bridge/opencensus/internal/ocmetric/metric.go#L95. But it shows as delta metric so the value is stacked.
<img width="880" alt="Screen Shot 2022-10-13 at 4 09 52 PM" src="https://user-images.githubusercontent.com/4332577/195726944-9af01538-3edf-4dfb-8d85-eb30742150b0.png">

**Comment by dashpole** [comment]
Hey @ktong, thanks for reporting the issue.

A few questions about your setup:

* What is the graph above showing?  Can you share the query you ran to get that graph?
* How is the OpenCensus metric being recorded (e.g. which package, or what instrument is being used to record it)?
* What version of opentelemetry-go and this repository are you using?
* Do you think this is an issue with this repository (something about our exporters), or with the bridge itself, or are you not sure?

Thanks!

**Comment by ktong** [comment]
Yes, it’s more likely caused by the issue.

**Comment by ktong** [comment]
> Hey @ktong, thanks for reporting the issue.
> 
> A few questions about your setup:
> 
> * What is the graph above showing?  Can you share the query you ran to get that graph?
MQL
```
fetch k8s_container
| metric 'workload.googleapis.com/grpc.io/server/completed_rpcs'
| group_by 1m, [value_completed_rpcs_mean: mean(value.completed_rpcs)]
| every 1m
```
> * How is the OpenCensus metric being recorded (e.g. which package, or what instrument is being used to record it)?
The View is defined at https://github.com/census-instrumentation/opencensus-go/blob/master/plugin/ocgrpc/server_metrics.go#L68
> * What version of opentelemetry-go and this repository are you using?
	go.opentelemetry.io/otel/metric v0.32.3
	go.opentelemetry.io/otel/sdk v1.11.0
	go.opentelemetry.io/otel/sdk/metric v0.32.3
	github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/metric v0.34.1

> * Do you think this is an issue with this repository (something about our exporters), or with the bridge itself, or are you not sure?
Not sure
> 
> Thanks!

**Comment by ktong** [comment]
The issue still exists while I upgrade go.opentelemetry.io/otel/sdk/metric to v0.33.0 which includes the fix of https://github.com/open-telemetry/opentelemetry-go/issues/3278.

**Comment by ktong** [comment]
reported another issue in opentelemetry-go: https://github.com/open-telemetry/opentelemetry-go/issues/3388

**Comment by dashpole** [comment]
Since the fix was merged upstream, i'm going to go ahead and close this issue.  Feel free to reopen if you think there is more to be done.
