### ISSUE TITLE
Update and review enabled linters

### ISSUE THREAD

**Issue by dashpole** [GoogleCloudPlatform/opentelemetry-operations-go#524]
Upstream otel-go recently had to change the linters they enable: https://github.com/open-telemetry/opentelemetry-go-contrib/issues/2896

We should update golangci-lint, and probably make some of the same changes.

**Comment by damemi** [comment]
I looked at some of our linters in https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/issues/416
It looks like we aren't using any of the deprecated linters mentioned upstream https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/main/golangci.yml#L114-L123
Maybe there are others that have been deprecated if we are several versions behind

**Comment by dashpole** [comment]
Should we enable more linters to match the set otel-go uses?

**Comment by damemi** [comment]
I'll open a PR to add them and see if they catch anything weird
