### ISSUE TITLE
Histogram type metrics with only one `+inf` bucket fails to export

### ISSUE THREAD

**Issue by ridwanmsharif** [GoogleCloudPlatform/opentelemetry-operations-go#525]
For `prometheus` metrics, The `+Inf` bucket must always be present, and will match the value of the `_count`.
When using GMP and using OTel to send metrics there we encounter an interesting error. The following metric fails to get exported to GMP even though it is valid:
```
# HELP kv_prober_write_latency Latency of successful KV write probes
# TYPE kv_prober_write_latency histogram
kv_prober_write_latency_bucket{le="+Inf"} 0
kv_prober_write_latency_sum 0
kv_prober_write_latency_count 0
```

This is from a CockroachDB prometheus exporter. It fails with the following error:
 ```
 {
            "error": "failed to export time series to GCM: rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: Field timeSeries[26].points[0].distributionValue had an invalid value: Distribution |explicit_buckets.bounds| does not have at least one entry.; Field timeSeries[6].points[0].distributionValue had an invalid value: Distribution |explicit_buckets.bounds| does not have at least one entry.; Field timeSeries[10].points[0].distributionValue had an invalid value: Distribution |explicit_buckets.bounds| does not have at least one entry.; Field timeSeries[142].points[0].distributionValue had an invalid value: Distribution |explicit_buckets.bounds| does not have at least one entry.; Field timeSeries[58].points[0].distributionValue had an invalid value: Distribution |explicit_buckets.bounds| does not have at least one entry.; Field timeSeries[111].points[0].distributionValue had an invalid value: Distribution |explicit_buckets.bounds| does not have at least one entry.\nerror details: name = Unknown  desc = total_point_count:200  success_point_count:194  errors:{status:{code:3}  point_count:6}"
        },
 ```

I believe this situation can be hit in the following way: If none of the buckets have a non-zero value they are not reported by exporters but the `+inf` bucket always is in prometheus. That would lead to this error.
 
Looks like our prometheus engine discards these: https://github.com/GoogleCloudPlatform/prometheus-engine/blob/83d012e29b74306dbee3e367270476ae86f4531a/pkg/export/transform.go#L292

Perhaps we should do something similar. Or adding in a `math.inf` bound in this case? Would that work?

**Comment by dashpole** [comment]
We don't want to deviate from the behavior of prometheus-engine, so for now we should discard those metrics.

**Comment by damemi** [comment]
@dashpole were you still working on this? If not I can pick it up. I've seen this error cause a lot of oncall noise so it's good to know what's causing it
