### ISSUE TITLE
GMP exporter should follow OTel -> Prometheus export conventions

### ISSUE THREAD

**Issue by dashpole** [GoogleCloudPlatform/opentelemetry-operations-go#543]
That includes:

* [x] Adding a `target_info` metric with resource attributes
* [x] Unit should be added as a suffix in metric names (before type suffixes)
* [x] Counters have a _total suffix added
* [x] otel_scope_info metric from scope
* [x] otel_scope_name and otel_scope_version attribute to all metrics within the scope, and to otel_scope_info

**Comment by dashpole** [comment]
I'm going to work on the metric name portion of this

**Comment by damemi** [comment]
Closing via #574

**Comment by damemi** [comment]
Just noticed we never enabled these upstream. Opened https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/24372 to add to contrib
