### ISSUE TITLE
Support gzip compression for metric export

### ISSUE THREAD

**Issue by dashpole** [GoogleCloudPlatform/opentelemetry-operations-go#544]
For off-GCP workloads, it can be helpful to reduce network bandwidth by enabling compression.  That can be done with something like this:  https://github.com/GoogleCloudPlatform/prometheus-engine/blob/2e01f7369ed284c77a401c63b53b145eeeec87b1/pkg/export/export.go#LL261C4-L261C55

It isn't clear to me if that can be used for all signal types, or just for monitoring

**Comment by aabmass** [comment]
"High p2" because this would be a very useful feature. Mike is still planning to work on this.
