### ISSUE TITLE
Automatic Credential Lookup in collector exporter make it not possible to set credentials

### ISSUE THREAD

**Issue by cpheps** [GoogleCloudPlatform/opentelemetry-operations-go#547]
[This](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/main/exporter/collector/config.go#L254-L266) block of code, add in #527, in `exporter/collector/config.go` does an automatic credentials lookup where it checks the existence of the `GOOGLE_APPLICATION_CREDENTIALS` ENV or the `application_default_credentials.json` file. If one is present it loads the credentials if not it errors. 

In our collector we have wrapped the `googlecloud` exporter to allow customers to specify a `credentials_file` or embed the credentials JSON in the config via a `credentials` parameter. Here's is our [config documentation](https://github.com/observIQ/observiq-otel-collector/tree/main/exporter/googlecloudexporter#configuration). We have customers that require this functionality for configuring more than one `googlecloud` exporter in an OTel collector. Primarily if they want to send data to multiple projects they have an exporter for each.

With the recent change to check for credentials we can no longer add our own credential config option as it is not taken into account in this logic and causes one of two behaviors:

1. If there are no default credentials it errors that none were found
2. If there are default credentials the gRPC client errors that multiple credentials were set (default one the ones we pass in).

It would be nice if this default lookup logic only occurred if no other credentials options were set.

**Comment by cpheps** [comment]
@dashpole 

> Does this problem exist for any option? Or are credentials the only place where multiple options is not permitted?

I believe it's just credentials. The validation logic lives in [google.golang.org/api](https://github.com/googleapis/google-api-go-client/blob/main/internal/settings.go#L80). Looks like it only worries about multiple credentials being set.

> Option 3 seems the least invasive, but option 4 might be worth considering as well.

I agree with this assessment. For option 4, I think we brought up adding the ability to specify non-default credentials before and at the time it didn't seem like this was something Google wanted to support at the time. Maybe that has since changed.

**Comment by dashpole** [comment]
Let's go with option 3 for now to fix the issue.

> We have customers that require this functionality for configuring more than one googlecloud exporter in an OTel collector. Primarily if they want to send data to multiple projects they have an exporter for each.

We do support [multi-project export](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/googlecloudexporter#multi-project-exporting) via the `gcp.project.id` resource attribute.  It is also possible to have multiple exporters send to different projects, but share the same credentials, so long as the credentials grant write access to both.

Out of curiosity, why did you decide to support both the json file (credentials_file) and the explicit configuration (credentials)?  I'm no oauth expert, but wouldn't the latter involve putting sensitive data in the collector config?

**Comment by cpheps** [comment]
Thanks for helping us out to fix the issue.

As far as the answer to multi project support this is driven by customer preference. I'm not deeply involved in the customer engagements but it is my understanding the customers wanted to keep credentials per project separate. I will notify our customer support team of the multi-project support you linked just in case they were not aware.

For embedding the credentials in the config. You are right this does put sensitive data into the config but it was a customer driven request, I believe for ease of use for configuring one or more exporters.

**Comment by cpheps** [comment]
@dashpole I'd like to reopen this issue. We just tried this with the latest release and I think the order of operations in this logic still causes and issue.

```go
creds, err := google.FindDefaultCredentials(ctx, scopes...)
if err != nil {
	return nil, fmt.Errorf("error finding default application credentials: %v", err)
}
if clientCfg.GetClientOptions == nil || len(clientCfg.GetClientOptions()) == 0 {
	// Only add default credentials if GetClientOptions does not
	// provide additional options since GetClientOptions could pass
	// credentials which conflict with the default creds.
	copts = append(copts, option.WithCredentials(creds))
}
```

Even if client options are set we still try to find default credentials first which will cause an error. I would think the call too `google.FindDefaultCredentials` should happen inside the if block.

**Comment by dashpole** [comment]
@cpheps How do you set the project id?  We currently need the credentials for the project id as well.  Would it be acceptable to throw an error if clientCfg.GetClientOptions() is set, and project ID is not set?

**Comment by cpheps** [comment]
Yeah I think that makes sense. 

We try to parse it if we can from the passed in credentials. If not the user can set it directly.

**Comment by dashpole** [comment]
@cpheps if you are able to try out #588 with your use-case, that would be helpful

**Comment by cpheps** [comment]
@dashpole Just tested it and this works as expected. Thanks for the quick fix.
