### ISSUE TITLE
Refactor collector logs exporter to support multi-project quota

### ISSUE THREAD

**Issue by damemi** [GoogleCloudPlatform/opentelemetry-operations-go#558]
https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/555 added multi-project quota support for traces and metrics, but the logs exporter currently batches log entries from potentially multiple projects into a single request.

Since the cross-project quota is set by a header on the request, the logs exporter will need to be refactored so that batches are composed of logs for the same destination project.

**Comment by dashpole** [comment]
Still useful
