### ISSUE TITLE
GCL exporter: Multi-log payloads duplicate labels

### ISSUE THREAD

**Issue by BinaryFissionGames** [GoogleCloudPlatform/opentelemetry-operations-go#572]
If a plog.Logs payload has multiple log entries, labels (attributes) from the first record will override labels on the second record.

It appears that this is because the labels map used when mapping the plog.Log to the google logging entry is re-used. See the following loop here; The same map is used in every iteration.
https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/8b0cedbe3f7ceaf529f60efec5003acff6975118/exporter/collector/logs.go#L226-L259

Here, the map is assigned as the entry's label map:
https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/8b0cedbe3f7ceaf529f60efec5003acff6975118/exporter/collector/logs.go#L403

And here, attributes are added to the label map, which will then be used when converting the next log record:
https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/8b0cedbe3f7ceaf529f60efec5003acff6975118/exporter/collector/logs.go#L414-L416

The solution seems to be to create a copy of the label map here, instead of just using an assignment.

**Comment by damemi** [comment]
Thanks for reporting this @BinaryFissionGames. I'll open a fix

**Comment by cpheps** [comment]
@damemi I'm curious if there is a timeline on when this fix going to be integrated into OTel? It seems like it would effect a lot of users sending logs to GCP.

**Comment by damemi** [comment]
@cpheps we're planning to cut a new release and bump upstream this week, then it should be available in the next version of the collector after that
