### ISSUE TITLE
GMP metric integration test is broken

### ISSUE THREAD

**Issue by dashpole** [GoogleCloudPlatform/opentelemetry-operations-go#584]
As part of https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/583, I found that the GMP tests are not passing when run against a real GCM endpoint.

Failure:
```
    metrics_integration_test.go:72: 
        	Error Trace:	/workspace/exporter/collector/integrationtest/metrics_integration_test.go:72
        	Error:      	Received unexpected error:
        	            	failed to export time series to GCM: rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: Request was missing field timeSeries[21].points[0].interval.endTime: The end time of the interval is required.; Request was missing field timeSeries[1].points[0].interval.endTime: The end time of the interval is required.
        	Test:       	TestIntegrationCollectorLogs/Google_Managed_Prometheus
```

**Comment by damemi** [comment]
I'll take a look into this, thanks @dashpole

**Comment by damemi** [comment]
At first I assumed I just needed to add a timestamp to the new metrics, but it's [already there](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/main/exporter/collector/integrationtest/testdata/fixtures/metrics/google_managed_prometheus_expect.json#L735).

This is set by the exporter calling [`timestamppb.New(point.Timestamp().AsTime())`](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/0c7cfa7a5ababcdd1440d1479cbc9d4df041fe08/exporter/collector/metrics.go#L896). I assume this just defaults to the zero time when it's not set. But, I'm wondering if this is working right for any of our points. For example, [this timestamp](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/0c7cfa7a5ababcdd1440d1479cbc9d4df041fe08/exporter/collector/integrationtest/testdata/fixtures/metrics/google_managed_prometheus.json#L340) is `Fri Apr 08 2022 18:45:16 GMT+0000` but comes out as [`1970-01-01T00:00:00Z`](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/0c7cfa7a5ababcdd1440d1479cbc9d4df041fe08/exporter/collector/integrationtest/testdata/fixtures/metrics/google_managed_prometheus_expect.json#L617). The rest of the timestamps in that expect fixture are also the zero time.

That still doesn't explain why this is failing for just these new metrics, so there's obviously something wrong with them in particular. But I thought this was interesting too.

**Comment by dashpole** [comment]
Are timestamps being set for target_info and scope_info?  That was the ones I assumed it impacted

**Comment by damemi** [comment]
@dashpole it is in the expect fixture: https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/9c0f81b80da79dce32aaff35814e21e8d9711bac/exporter/collector/integrationtest/testdata/fixtures/metrics/google_managed_prometheus_expect.json#L708-L739 (sorry think I messed up the permalink in my other comment)

**Comment by dashpole** [comment]
I removed the metrics in question from the fixture in the previous PR: https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/583/files#diff-e2bf93fa07e3c8d6067f0b4847f1c665899433fb5797f4d81a54d969d2664aecL60

It isn't clear to me if the expectation's timestamp is overridden by the test fixture sanitization or if it is actually set beforehand.  Maybe when we override timestamps in the test, we should make they are not zero first, or output an error?

**Comment by damemi** [comment]
Ah right, when we record fixtures we normalize them with an empty timestamp. That's probably why they were already in the expect fixture for target_info. It's [supposed to only do it if the end time is nil](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/e22e262f57389dba8bb237900311c34e496237e0/exporter/collector/integrationtest/testcases/testcase.go#L359-L361), so I'm not sure how it got set at some point. But this is something for me to look at

**Comment by dashpole** [comment]
Maybe its non-nil, but set to zero?
