### ISSUE TITLE
PushLogs in exporter can get stuck in infinite loop

### ISSUE THREAD

**Issue by cpheps** [GoogleCloudPlatform/opentelemetry-operations-go#590]
In [PushLogs](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/main/exporter/collector/logs.go#L174) the exporter can get stuck in an infinite loop if a batch is large enough to be split over several requests to GCP.

If a batch needs to be split after the first request `currentBatchSize` is not reset with the rest of the loop variables [here](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/main/exporter/collector/logs.go#L215-L216). This leads to the next iteration that the entry at index 0 will be calculated as too large. ~~I believe there is an off by one error in the slicing logic which will end up sending an empty request.~~

```go
_, err := l.writeLogEntries(ctx, entries[:entry])
if err != nil {
	errors = append(errors, err)
}

entries = entries[entry:]
```

In the above code when `entry` is 0 `entries[:entry]` will be an empty slice and `entries[entry:]` will reset to the same slice. Since we never reset `currentBachSize` and we keep iterating over the same slice, `PushLogs` will keep sending empty requests.

**Comment by cpheps** [comment]
Just to correct I think there isn't an off by one error with the slicing but rather that when `entry` is 0 it's a special case.

**Comment by damemi** [comment]
Thanks for finding this @cpheps. I imagine this was the cause of the memory leak/high request counts we were seeing recently?

Opened https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/591 to fix this and add an integration test.

**Comment by cpheps** [comment]
@damemi Yes this seemed to be the main issue when using large batch sizes with the batching processor.

**Comment by damemi** [comment]
@cpheps yes, the pull request to update this in v0.72.0 upstream is already open here: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18755. It's been approved and should make it into the next upstream release, pending merge by upstream maintainers.

**Comment by cpheps** [comment]
Oh thanks! I searched through the contrib PRs and guess I missed it. Appreciate the link.
