### ISSUE TITLE
Update to recent version creates memory leak like issue and the byte sent to google continue increases

### ISSUE THREAD

**Issue by liufuyang** [GoogleCloudPlatform/opentelemetry-operations-go#595]
We tried to updated opentelemetry-operations-go to the newest packages [see here](https://github.com/einride/cloudrunner-go/pull/401), but then we noticed this memory leak like issue and the byte sent to google continued increases:

<img width="925" alt="image" src="https://user-images.githubusercontent.com/161689/219864215-29cf87ae-1b4b-4373-a2f6-297d6c008987.png">

<img width="1404" alt="image" src="https://user-images.githubusercontent.com/161689/219864449-bf45a836-825b-4a14-b7b8-f95003682b0d.png">

We tried to update to an earlier version last week and saw the same issue.
We thought this could be related to https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/issues/590, but after that is fixed and we now tried again, seems the issue remains.

Could there still be some batch export-related bugs exist? 

Or could it be because we configured the metric exporter wrongly?

Let me know if you need extra information. The package version used can be seen in the our PR doing the upgrades https://github.com/einride/cloudrunner-go/pull/401

Thank you.

**Comment by liufuyang** [comment]
Or perhaps it is a problem rooted from here? https://github.com/open-telemetry/opentelemetry-go/pull/3695

**Comment by damemi** [comment]
Hi @liufuyang, thanks for reporting this. It sounds like the issue you're seeing is related to metrics export, is that right? If so, #590 is a different issue which only affect the logs exporter.

To help with your issue, have you tried isolating it to see if it's a problem with the GCP libraries, or the upstream opentelemetry-go-contrib library? One way to do this would be to use a different exporter like the logging or file exporter and compare the resource profiles.

**Comment by liufuyang** [comment]
Hey @damemi, thank you so much for the fast feedback. I am not sure if I could have time to play with different exporters and I have limited knowledge in this domain.

But my guess is that it could be related to the issue from contrib packages, so I am waiting for the next 0.37 to be released and try again on our side as it includes a memory leak issue fix on that version https://github.com/open-telemetry/opentelemetry-go/milestone/40?closed=1

**Comment by dashpole** [comment]
It definitely could be related to https://github.com/open-telemetry/opentelemetry-go-contrib/issues/3071.

**Comment by liufuyang** [comment]
Yes, we just verified that:

1. with this https://github.com/open-telemetry/opentelemetry-go/pull/3695 in their next release, the memory issue can be fixed.
2. for the "high metric cardinality" issue (stated in the 3071 issue above) we could sort of get around by using the filters.

So not sure if we want or can do something about 2 here, otherwise I guess we can close this issue here now :)

**Comment by dashpole** [comment]
I'd say lets close this, and watch 3071.  If there is something we need to do in the exporter, we can reopen.

**Comment by liufuyang** [comment]
Great, thank you very much :)
