### ISSUE TITLE
Authenticating with `gcloud auth login` on GCE does not seem possible

### ISSUE THREAD

**Issue by braydonk** [GoogleCloudPlatform/opentelemetry-operations-go#614]
The docs for the [Google Cloud Exporter in opentelemetry-collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/googlecloudexporter#google-cloud-exporter) suggest that I get credentials through the command `gcloud auth application-default login`. When I run `gcloud auth application-default login` on a GCE VM, I get the following JSON shape:
```
{
  "client_id": "redacted",
  "client_secret": "redacted",
  "quota_project_id": "my-project-id",
  "refresh_token": "redacted",
  "type": "authorized_user"
}
```
This causes the exporter to fail with the following error:
```
Error: failed to build pipelines: failed to create "googlecloud" exporter, in pipeline "metrics/*": no project found with application default credentials
```
This is because the creds found by `google.FindDefaultCredentials` don't have a field `ProjectID`. https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/16f0ea8ce52bbbe71d4cbac84e5317c83d7324b6/exporter/metric/cloudmonitoring.go#L38-L47

I am unsure if this is a GCE specific problem. If it isn't, then the documentation should be revisited. However, it is very possible that this is a GCE specific problem and perhaps a note can be added to the documentation if anything.

**Comment by damemi** [comment]
My last comment was a lot of rambling. I opened https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/621 to update our docs with better recommendations for authenticating based on environment. tl;dr we shouldn't be telling people to use `gcloud auth application-default login` except for personal testing. If this looks good I'll add the same change to the upstream docs too.

Longer term, we will need to look more at our auth story (specifically our dependency on project id) and make sure it functionally aligns with the client libraries. For now though, I think this is WAI, just poorly documented.
