### ISSUE TITLE
Support bool-valued metrics in Cloud Monitoring Exporter

### ISSUE THREAD

**Issue by ItsLastDay** [GoogleCloudPlatform/opentelemetry-operations-go#624]
My team is maintaining an OTel collector. We provide this collector to other teams at Google. Those teams use the collector to gather metrics about their VMs/clusters/... .

Usecase that we've observed a couple of times: people want to have bool- and string-valued metrics. This is [allowed](https://cloud.google.com/monitoring/api/v3/kinds-and-types#kind-type-combos) by Cloud 
Monitoring, but not expressable in OTel: only [NumberDataPoint](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/metrics/v1/metrics.proto#L197) is available as a Gauge value. When users try to send an int-valued metric point instead of bool, googlecloudexporter returns an error. I assume the same happens with string-valued metric.

Thus, our users built forks of googlecloudexporter: they attach a label to a metric point (or maybe to a resource - I don't remember exactly), and in this forked exporter they check the presence of such label. If the label is present, they change the submitted value type, and delete the label.

We would like to have a similar functionality built into googlecloudexporter natively.

**Comment by lepan-google** [comment]
Hey open-source OpenTelemetry team, our team is using the Google Cloud Exporter to send metrics to Google Cloud Monitoring. We want to collect some metrics such as service status, component health, tool installation status, os versions, etc. We have 13 bool- and 1 string- metrics, and these are not supported by Google Cloud Exporter right now. We really hope this feature can be get integrated into Google Cloud Exporter.

**Comment by damemi** [comment]
@psx95 is going to be working on this

**Comment by lepan-google** [comment]
That's great to know! Thanks for the update! @damemi @psx95

**Comment by psx95** [comment]
After some discussions, we decided not to support String metrics. Only the support for boolean valued metrics will be added.

**Comment by psx95** [comment]
#637 Adds support for booleans in the exporter/collector.
