### ISSUE TITLE
k8s_container monitored resource type requires `cloud.platform: gcp_kubernetes_engine` even when running outside of Google Cloud

### ISSUE THREAD

**Issue by jsirianni** [GoogleCloudPlatform/opentelemetry-operations-go#627]
In the past, we were able to send logs to Cloud Logging by setting the following resource attributes
- k8s.container.name
- k8s.pod.name
- k8s.namespace.name
- k8s.cluster.name

Recently, I noticed that my logs are no longer shown under the `k8s_container` [monitored resource type](https://cloud.google.com/monitoring/api/resources#tag_k8s_container), instead they appear as `generic_node`.

This is because the [internal/resourcemapping/resourcemapping.go](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/main/internal/resourcemapping/resourcemapping.go#L171) is checking specifically for `cloud.platform: gcp_kubernetes_engine`.

We work with many Google customers who operate Kubernetes clusters outside of Google Cloud, therefore, the requirement for `cloud.platform: gcp_kubernetes_engine` is surprising, especially when using OpenTelemetry.

I can reproduce this with Minikube running on my workstation.

**With cloud.platform set**

Using the resource attribute processor, I can set the cloud.platform value to "trick" the exporter.

![Screenshot from 2023-04-21 19-13-48](https://user-images.githubusercontent.com/23043836/233747480-d0787177-d959-40e9-b10c-470f51dc2135.png)

**without cloud.platform**

If I do not add the attribute, my logs come through but as `generic_node`.

![Screenshot from 2023-04-21 19-13-22](https://user-images.githubusercontent.com/23043836/233747448-ea511b5c-b604-42d8-aab5-019e961f6bfe.png)

**Comment by damemi** [comment]
Hi @jsirianni, it looks like the line you're referring to has been part of the resource mapping for at least ~2 years based on the blame: https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blame/3a2c57209765f4752bd140a007612a81f58489c1/exporter/collector/monitoredresource.go#L131 (moved from that file to resourcemapping.go in https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/commit/f4bd197fc2ab1bffebdfd9dcc3547c348b403ccc ~1 year ago), so maybe it is a different change that has caused this behavior to show up recently for you. Do you know what version of these modules you were using when this worked, or if you've recently upgraded them?

**Comment by damemi** [comment]
Talked to the team and it sounds like this may have possibly been due to us originally writing to `gke_container`. We can look more into this in an upcoming sprint but unless a hard reason comes up for why we are strictly relying on GKE then we will probably open this up.

**Comment by dashpole** [comment]
Seems like if it is mapped to any hosted kubernetes cloud.platform (e.g. EKS, AKS, etc), then we should map to k8s_container.

**Comment by damemi** [comment]
Opened https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/683 to fix this

**Comment by damemi** [comment]
This should be fixed in the next release with #683, and anything that sets `k8s.cluster.name` should be, at minimum, mapped to `k8s_cluster`. Also opened issues in js, python, and java repos to make sure the behavior matches.
