### ISSUE TITLE
Logs without timestamps are skewed after a network outage

### ISSUE THREAD

**Issue by jmwilliams89** [GoogleCloudPlatform/opentelemetry-operations-go#639]
## Observed Behavior
If a network outage occurs and retry on failure is enabled, queued logs without timestamps will be given a much newer timestamp than expected. This is because the current time is assigned only when the google logging entry is created and not when logs reach the exporter for the first time. If a user does not understand this behavior beforehand, this can appear as an unexplained clock skew after an outage.

## Potential Solution
This could be solved by defaulting to the observed timestamp of the log when a timestamp does not exist, as noted here: https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/7e416c3ba3a366ddcc8791a738af17d1610eacd2/exporter/collector/logs.go#L385

**Comment by damemi** [comment]
Thanks @jmwilliams89, will look into fixing this. In the meantime, you can probably use a transform processor in your collector to set the timestamp you want as a workaround. But we should try to fall back to the observed_time when available.

**Comment by damemi** [comment]
This should be fixed by #640 and will be in the next release
