### ISSUE TITLE
Question: How to configure TemporalitySelector of gcp metric exporter?

### ISSUE THREAD

**Issue by shohei-ihaya** [GoogleCloudPlatform/opentelemetry-operations-go#670]
Hello, thanks for working on this great library!

I'm wondering how to configure TemporalitySelector of GCP exporter.
By default, CumulativeTemporality is used but I wanna set DeltaTemporality for some of metrics.

In case of stdout exporter you can configure in [this way](https://github.com/open-telemetry/opentelemetry-go/blob/main/exporters/stdout/stdoutmetric/config.go#L79-L85) 

Is there any plan to implement `WithTemporalitySelector` func for GCP exporter? or can I configure TemporalitySelector in another way?

**Comment by dashpole** [comment]
I don't think google cloud monitoring supports delta metrics for custom metrics right now.  The [docs](https://cloud.google.com/monitoring/api/v3/kinds-and-types#kind-type-combos) only list custom.googleapis.com as not allowing deltas, but I believe it applies to all customer-facing domains (workload, prometheus, external).googleapis.com as well.

**Comment by shohei-ihaya** [comment]
Thank you for quick reply!

> cloud monitoring supports delta metrics for custom metrics

I understand, thanks again!
