### ISSUE TITLE
Untyped metrics are incorrectly named when metric name normalization is enabled.

### ISSUE THREAD

**Issue by dashpole** [GoogleCloudPlatform/opentelemetry-operations-go#677]
Found while working on https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/674.

`prometheus.BuildPromCompliantName` builds a metric name based on the name, unit, and type.  For sums, it adds a `_total` suffix.

If you have an unknown gauge metric named `fake.untyped.metric`, it is renamed to `fake_untyped_metric_total` for the counter version.  Ideally, we should use the compliant name it would have if it was a gauge for the unknown metric.

Want:
```diff
[
  {
    "metric": {
      "type": "prometheus.googleapis.com/fake_untyped_metric/unknown",
      "labels": {
        "ex_com_lemons_untyped": "13"
      }
    },
    "resource": {
      "type": "prometheus_target",
      "labels": {
        "cluster": "",
        "instance": "",
        "job": "",
        "location": "",
        "namespace": ""
      }
    },
    "metricKind": "GAUGE",
    "valueType": "DOUBLE",
    "points": [
      {
        "interval": {
          "endTime": "1970-01-01T00:00:00Z"
        },
        "value": {
          "doubleValue": 3
        }
      }
    ]
  },
  {
    "metric": {
-      "type": "prometheus.googleapis.com/fake_untyped_metric_total/unknown:counter",
+      "type": "prometheus.googleapis.com/fake_untyped_metric/unknown:counter",
      "labels": {
        "ex_com_lemons_untyped": "13"
      }
    },
    "resource": {
      "type": "prometheus_target",
      "labels": {
        "cluster": "",
        "instance": "",
        "job": "",
        "location": "",
        "namespace": ""
      }
    },
    "metricKind": "CUMULATIVE",
    "valueType": "DOUBLE",
    "points": [
      {
        "interval": {
          "endTime": "1970-01-01T00:00:00Z",
          "startTime": "1970-01-01T00:00:00Z"
        },
        "value": {
          "doubleValue": 3
        }
      }
    ]
  }
]
```

**Comment by dashpole** [comment]
cc @damemi

**Comment by damemi** [comment]
I did notice this while I was working on it, but I thought adding the name normalization in this case made sense due to it being converted to a sum. I'll double check what the prom receiver and GMP do and match that.

**Comment by damemi** [comment]
Ok, double checking it and agree this should be fixed. The Prom receiver just converts unknown to gauges, and GMP doesn't do any name normalization which makes sense because it's just getting the metric names anyway. I'll open a PR
