### ISSUE TITLE
Update usages of `faas.id` resource attribute to `faas.instance`

### ISSUE THREAD

**Issue by damemi** [GoogleCloudPlatform/opentelemetry-operations-go#679]
Our resource detectors and monitored resource mappings currently rely on semconv v1.18, which has [`faas.id`](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.18.0/specification/resource/semantic_conventions/faas.md#faas-resource-attributes), which we use for the Generic Task (Cloud Run) resource.

As of semconv v1.19.0, [`faas.id` is removed](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.19.0/specification/resource/semantic_conventions/faas.md#faas-resource-attributes)(/replaced with [`cloud.resource_id`](https://github.com/open-telemetry/opentelemetry-specification/pull/3188)).

So, when we update to semconv v1.19, we'll need to update our usages of `faas.id` to `faas.instance`:

* Upstream resource detection processor: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/02f688dd0e96cd10bb23a030739887570533e61d/processor/resourcedetectionprocessor/internal/gcp/gcp.go#L89-L91
* [genericTask resource mapping](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/b6fc3f0d850c1512de3a2a22bcba9904843eb6bd/internal/resourcemapping/resourcemapping.go#L140)
  * [also parsed in the mapping switch statement](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/b6fc3f0d850c1512de3a2a22bcba9904843eb6bd/internal/resourcemapping/resourcemapping.go#L201)
* [FaasID detector function (for reference, won't need to be updated)](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/b6fc3f0d850c1512de3a2a22bcba9904843eb6bd/detectors/gcp/faas.go#L91)

This attribute is also used in our code samples for GMP-Cloud Run integration: https://github.com/GoogleCloudPlatform/golang-samples/blob/e4eddad4457dc10f0fabb1b6f4c1906bea46aedc/run/custom-metrics/collector/collector-config.yaml#L45, which will need to be updated and the matching docs pages manually redeployed.

**Comment by dashpole** [comment]
Proposed Plan:

1. Update GMP exporter to map `faas.name` to `job`, and `faas.instance` to `instance`.
2. Update e2e test framework to expect the new attribute.
3. Update Resource detectors (across languages) to detect `faas.instance` instead of `faas.id`, and update metric exporter mapping.
4. Wait ~3 months to give time for collector releases to happen.
5. Remove the resource processor from the sample.

For anyone using our current documentation, they would not be broken at any point.

@aabmass do you think that plan makes sense?

**Comment by aabmass** [comment]
SGTM. Do we consider this breaking for the genericTask mapping Mike mentioned? This would apply to users sending to Cloud Monitoring (not GMP). I think it should be ok

**Comment by dashpole** [comment]
It is breaking unless they are using our resource detector, which seems OK.  We should recommend people use our resource detectors wherever possible.

**Comment by dashpole** [comment]
I need to update contrib for golang before I can update the this repo

**Comment by dashpole** [comment]
The collector's resource detector needs to be updated.  I had forgotten about that.

**Comment by aabmass** [comment]
> As of semconv v1.19.0, [`faas.id` is removed](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.19.0/specification/resource/semantic_conventions/faas.md#faas-resource-attributes)(/replaced with [`cloud.resource_id`](https://github.com/open-telemetry/opentelemetry-specification/pull/3188)).
> 
> So, when we update to semconv v1.19, we'll need to update our usages of `faas.id` to `faas.instance`

Sorry it's been a while and I'm confused again. If `faas.id` was renamed to `cloud.resource_id`, shouldn't we be using that? Or were we incorrectly using `faas.id` in the first place?

**Comment by dashpole** [comment]
We were incorrectly using faas.id in the first place.  `faas.id` was meant to be the full resource name (e.g. projects/my-project/locations/us-central1/functions/my-function)
