### ISSUE TITLE
trace export failing with "Missing span display name!"

### ISSUE THREAD

**Issue by k4leung4** [GoogleCloudPlatform/opentelemetry-operations-go#687]
`failed to export to Google Cloud Trace: rpc error: code = InvalidArgument desc = Missing span display name!"`

I'm seeing the above error, which seems weird, as all span should have a name defaulted when converting to proto form
https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/main/exporter/trace/trace_proto.go#L149-L151

not sure how it is happening

any guidance to better debug this would be appreciated, as this is running in a relatively complex system, it is not clear to me where these traces are even originating from

**Comment by dashpole** [comment]
Is it possible the span name is empty?  e.g. someone did `tracer.Start(ctx, "")` somewhere?

**Comment by dashpole** [comment]
I can't think of any other way that would be empty

**Comment by punya** [comment]
Closing because the customer didn't respond in a few months.
