### ISSUE TITLE
Update exporter/trace version to 0.2.1

### ISSUE THREAD

**Issue by radev** [GoogleCloudPlatform/opentelemetry-operations-go#69]
Tag for exporter/trace/v0.2.1 is missing:

`GOPROXY=direct go get github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/trace@v0.2.1` results in `invalid version: unknown revision exporter/trace/v0.2.1`

**Comment by radev** [comment]
Related to #38

**Comment by nilebox** [comment]
@james-bebbington could you please create additional tags?

FWIW the process of tagging all Go Modules is now automated in the collector contrib repo: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/10f7771ece0d71d747ad9a936c11a348d66471d6/Makefile#L65-L73

We may want to adopt their code to automate our release process.

**Comment by james-bebbington** [comment]
Sorry - have added tags now 🤦

Will look into https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/issues/70 when doing the next release
