### ISSUE TITLE
[collector trace exporter] Work around Cloud Trace attribute size limits by copying event-level stacktrace to span-level

### ISSUE THREAD

**Issue by punya** [GoogleCloudPlatform/opentelemetry-operations-go#694]
### Context

* Cloud Trace imposes a low limit (either [256 bytes][1] or [16kB][2] depending on where you look) on span and attribute labels, but provides a special label or a dedicated proto field for stacktraces (which can be up to 10MB).
* Because OTel represents stacktraces as event attributes, most of them end up getting truncated, resulting in greatly reduced troubleshooting value.

### Proposal

* Add a config option to the Cloud Trace exporter, which copies the un-truncated event-level stacktrace to one of the span-level choices that would permit larger values.
* If a span has multiple events, choose the one that's chronologically latest.
* Make this config option be on by default.

[1]: https://cloud.google.com/trace/docs/quotas#:~:text=Size%20of%20key,128%20bytes
[2]: https://cloud.google.com/trace/docs/reference/v1/rest/v1/projects.traces#TraceSpan.FIELDS.labels:~:text=be%20less%20than-,16%20kilobytes

**Comment by punya** [comment]
Going to close this out in favor of a different server-side approach we want to explore first.

**Comment by nioncode** [comment]
@punya Is there another issue that we can subscribe to for updates? I'm currently attaching stacktraces via opentelemetry (although from java, but seems like this does not matter) and they get truncated after 256 byte in the cloud trace ui, which makes them kind of unusable. Is there any workaround that we can implement?

**Comment by punya** [comment]
Hi @nioncode. We're actively working on relaxing this limitation on the server-side, but there's no public tracker or workaround at the moment.
