### ISSUE TITLE
Stackdriver exporter event attributes aren't displayed. 

### ISSUE THREAD

**Issue by rghetia** [GoogleCloudPlatform/opentelemetry-operations-go#7]
Originally opened at https://github.com/open-telemetry/opentelemetry-go/issues/460 by @shanna

Span events with string or bool attributes don't show in the stackdriver UI. I'm not 100% this is an open-telemetry stackdriver exporter issue or a stackdriver tracing issue. I don't have a standalone test case for you but it's easy to reproduce:

go.opentelemetry.io/otel v0.2.1
go.opentelemetry.io/otel/exporter/trace/stackdriver v0.2.1
Example:

// ...
span.AddEvent(ctx, "example-event",
	core.Key("example-string").String("foo"),
	core.Key("example-int").Int(123),
	core.Key("example-bool").Bool(true),
)
All the keys appear in the stackdriver UI but only the value 123 is displayed, all other attributes are empty.
If I use the stdout exporter or just %+v the span I can see all the attributes exist.
The set of attributes appears to be valid according to Googles v2 documentation.

**Comment by damemi** [comment]
I don't think this is relevant anymore based on the package versions
