### ISSUE TITLE
Google Cloud Logging exporter converts resource labels from . to _

### ISSUE THREAD

**Issue by solsu01** [GoogleCloudPlatform/opentelemetry-operations-go#722]
This was discovered when testing Cloud Logging's ability to detect service names. Cloud Logging is looking for service.name as per OTel conventions but logs were emitted with service_name instead.

We believe the issue is related to https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/main/exporter/collector/logs.go#L253 which leads to Cloud Monitoring label updates per https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/main/exporter/collector/metrics.go#L1310

We should not be applying these conversions for logging labels.

**Comment by dashpole** [comment]
From https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry, it appears there is no restriction on the strings that are allowed.  I'll assume we still want to ensure it is UTF-8
