### ISSUE TITLE
Import error sdk/metric/aggregation

### ISSUE THREAD

**Issue by maciejrozanski** [GoogleCloudPlatform/opentelemetry-operations-go#726]
After trying to run example from:
https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/tree/main/exporter/metric

```
go: finding module for package go.opentelemetry.io/otel/sdk/metric/aggregation
go: xxx imports
        github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/metric imports
        go.opentelemetry.io/otel/sdk/metric/aggregation: module go.opentelemetry.io/otel/sdk/metric@latest found (v0.41.0), but does not contain package go.opentelemetry.io/otel/sdk/metric/aggregation
```

**Comment by dashpole** [comment]
We just need to update to the latest version to fix this (https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/728).  If you want to work around this, you can downgrade your sdk/metric package version in your go.mod to `v0.41.0`
