### ISSUE TITLE
[security] audit repository tooling

### ISSUE THREAD

**Issue by dashpole** [GoogleCloudPlatform/opentelemetry-operations-go#734]
Even though this repository isn't in the OTel github organization, we should still try to follow best practices used by the rest of the go community: https://github.com/open-telemetry/opentelemetry-go/issues/4459.

We should look at the list of recommendations, determine what we need to change, and make updates to this repository if possible.

- [ ] CodeQL enabled via [GitHub Actions](https://github.com/open-telemetry/opentelemetry-collector/blob/main/.github/workflows/codeql-analysis.yml)
- [x] Static code analysis tool (the collector uses govulncheck [https://pkg.go.dev/golang.org/x/vuln] on every build)
- [ ] Repository security settings
    - [ ] Security Policy ✅
    - [x] Security advisories ✅
    - [x] Private vulnerability reporting ✅
    - [x] Dependabot alerts ✅
    - [x] Code scanning alerts ✅

**Comment by aabmass** [comment]
David to look into this next sprint

**Comment by dashpole** [comment]
codeql is not using github actions.  I need to look into that.
