### ISSUE TITLE
Collector exporter does not log errors when requests fail

### ISSUE THREAD

**Issue by dashpole** [GoogleCloudPlatform/opentelemetry-operations-go#761]
After removing retry_on_failure in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/25900, we no longer get any log messages when we fail to send.

Discovered in https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/issues/760.

**Comment by aabmass** [comment]
Looking at the original PR, its very weird that this removed logging. I would have expected the collector to log errors for you even without exporterhelper. Do you think there is an upstream collector bug here?

**Comment by dashpole** [comment]
Opened https://github.com/open-telemetry/opentelemetry-collector/issues/8791 and https://github.com/open-telemetry/opentelemetry-collector/pull/8792.  We can hold off fixing it here until those are resolved.

**Comment by dashpole** [comment]
Fixed by https://github.com/open-telemetry/opentelemetry-collector/pull/8792
