### ISSUE TITLE
Metrics created from a cloud_run_revision have resource type generic_node

### ISSUE THREAD

**Issue by dgnemo** [GoogleCloudPlatform/opentelemetry-operations-go#762]
Metrics uploaded to Cloud Monitoring from a Cloud Run service
(despite initializing otel with the GCP resource detector), have "Resouce Type: `generic_node`

If this could be fixed in a coming release it would be amazing. Thanks.

**Comment by dashpole** [comment]
Thanks @dgnemo!  This is on our radar, and we will try to have this done soon.
We are tracking it in https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/issues/735, so i'll close this if thats alright.
