### ISSUE TITLE
Question: support for customized cloud.provider

### ISSUE THREAD

**Issue by shohei-ihaya** [GoogleCloudPlatform/opentelemetry-operations-go#767]
Thanks for the great library.

I have a question about metrics with [Cloud Resource Attributes](https://opentelemetry.io/docs/specs/semconv/resource/cloud/).

I am sending metrics with googlecloud exporter.

If I set the resource attribute by resourcedetection processor with the environment variable `OTEL_RESOURCE_ATTRIBUTES="cloud.platform=linode_instance,cloud.provider=linode"`, the metrics are not displayed in the console.

Without the resource attribute `cloud.xxx`, metrics will be displayed as generic nodes or generic tasks.

Is the customized `cloud.xxx` resource attribute not supported?

**Comment by dashpole** [comment]
Are you using the collector exporter (in collector-contrib), or the in-process metrics exporter (exporter/metrics)?

You should be able to provide those attributes, but we generally use them to map to Monitored Resources in Cloud Monitoring.  If you want them to show up explicitly, you can set the resource filter to add them as metric attributes: [WithFilteredResourceAttributes](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/0b578e83295fd5efb3a3d22bc9473743abd31ec5/exporter/metric/option.go#L120)

**Comment by shohei-ihaya** [comment]
Thanks for quick reply.

I'm using collector exporter (in collector-contrib).

> If you want them to show up explicitly, you can set the resource filter to add them as metric attributes: [WithFilteredResourceAttributes](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/0b578e83295fd5efb3a3d22bc9473743abd31ec5/exporter/metric/option.go#L120)

I understand, I will try. thanks!

**Comment by aabmass** [comment]
@shohei-ihaya did that solve your problem?

**Comment by shohei-ihaya** [comment]
@aabmass 
Actually no.
I gave up storing customized value in resource parameter, and now I store them in metric attributes

**Comment by aabmass** [comment]
I believe the option David mentioned should do that for you automatically if that's easier.

To be clear, Cloud Monitoring has strict schema for monitored resource and can only store the predefined keys. If you want other resource attributes, they have to be put as metric attributes for now. Given that you got it working that way, I'm going to close as "working as intended". Feel free to re-open if needed
