### ISSUE TITLE
Fall back to k8s.cluster.id when k8s.cluster.name is not available

### ISSUE THREAD

**Issue by dashpole** [GoogleCloudPlatform/opentelemetry-operations-go#771]
Only GKE currently supports detecting k8s.cluster.name (although EKS support is in progress).  To provide a better default experience on non-GKE kubernetes clusters, we should fall back to k8s.cluster.id.

This will require changes to:

* internal/resourcemapping/resourcemapping.go
* https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/1d581fe1c7d783e2bfcde5d6b1b8422b9dfd479f/exporter/collector/googlemanagedprometheus/monitoredresource.go#L44

**Comment by aabmass** [comment]
This would be helpful for minkube clusters which don't have a name
