### ISSUE TITLE
Exemplars should be sorted in Collector exporter

### ISSUE THREAD

**Issue by jsuereth** [GoogleCloudPlatform/opentelemetry-operations-go#778]
@franciscovalentecastro discovered in #777 that we need to make sure exemplars are sorted when sending to Cloud Monitoring or the points will be rejected.

We've been lucky so far, as most exemplars have come from explicit bucket histograms, where they are implicitly sorted.

**Comment by franciscovalentecastro** [comment]
This is the error i got when hooking up the go export of `Exponential Histograms` with the Exemplars from the algorithm implemented in https://github.com/open-telemetry/opentelemetry-go/pull/4455.

```
2023/12/14 19:14:57 rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: Field timeSeries[0].points[0].distributionValue had an invalid value: Distribution |bucket_options.exponential_buckets| has out-of-order/duplicate exemplars.
error details: name = Unknown  desc = total_point_count:2 success_point_count:1 errors:{status:{code:3} point_count:1}
```
