### ISSUE TITLE
Update CheckpointSet iteration to use the exporter as KindSelector

### ISSUE THREAD

**Issue by james-bebbington** [GoogleCloudPlatform/opentelemetry-operations-go#78]
Update CheckpointSet iteration to use the exporter as KindSelector instead of explicitly passing CUMULATIVE. See this comment thread for more details: https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/73#discussion_r461247340. Also note this is somewhat dependent on future changes to the SDK.

In addition to this, we should add integration tests to validate DELTAs are exported correctly as described here: https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/73#pullrequestreview-455207323

**Comment by dashpole** [comment]
This is probably obsolete as we are rewriting the metrics exporter.
