### ISSUE TITLE
Add checklicense to Makefile & CI

### ISSUE THREAD

**Issue by james-bebbington** [GoogleCloudPlatform/opentelemetry-operations-go#81]
We should add a checklicense target to validate licenses are appended to source files going forward. We can do something similar to Otel Go - see: https://github.com/open-telemetry/opentelemetry-go/blob/master/Makefile#L145

Note however that some code in this repo was authored by contributors who signed the OpenTelemetry CLA so we need to retain this different license info for some existing files.

**Comment by nilebox** [comment]
> Some of them incorrectly state OpenTelemetry authors instead of Google Inc.

See https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/issues/16#issuecomment-624917221, this is not a mistake.

Can we make `licensecheck` not complain about different licenses in the repo?

**Comment by james-bebbington** [comment]
Thanks for the link & info. I have updated this issue description with that info so as not to confuse anyone. The license check has to be run per file so we could do a different check for a hard coded list of files that have the OpenTelemetry license (that won't change).

**Comment by aabmass** [comment]
Added google cloud license check github app and config in #139
