### ISSUE TITLE
Use the Version number to insert g.co/agent/component attribute

### ISSUE THREAD

**Issue by james-bebbington** [GoogleCloudPlatform/opentelemetry-operations-go#82]
Use the version number in trace/version.go, which is automatically updated by the release scripts, to set the `g.co/agent/component` attribute for traces to the value `opentelemetry-go <ot_version>; google-cloud-<trace|metric>-exporter <exporter_version>`

Use the version number in metric/version.go, which is automatically updated by the release scripts, to set the user agent string supplied to Cloud Monitoring to the same value.

For reference, see [requirements doc](https://docs.google.com/document/d/1eeGeSYlE2F-Dc-5_yLXnIlj7e--BYFeWlzWy6qBV2cg/edit#heading=h.aoqug1blgfpl)

In either case, the user should be able to override this value by passing in a UserAgent string explicitly

**Comment by punya** [comment]
@james-bebbington it looks like the `g.co/agent` attribute is already being populated in the way that you describe: https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/227b0dcdc39db4cfc82225b0078a9533aa8cc25a/exporter/trace/trace_proto.go#L62

and `g.co/component` isn't fully specified (potentially obsolete?). Can we close out this issue?

**Comment by james-bebbington** [comment]
Yea I think the `/component` text was as typo here.

Yes this can be closed. It looks like https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/105 resolved this bug and I forgot to close it.
