### ISSUE TITLE
Export Exponential Histogram to Managed Prometheus doesn't work due to unimplemented naming convertion

### ISSUE THREAD

**Issue by alexvanboxel** [GoogleCloudPlatform/opentelemetry-operations-go#841]
The Google Managed Prometheus naming doesn't support the `pmetric.MetricTypeExponentialHistogram`; this makes the export of Exponential Histograms fail.

https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/21602689459a185ee389b4ea871b392de5a010ef/exporter/collector/googlemanagedprometheus/naming.go#L54

I think adding the following will fix the issue. But I don't know what the correct Suffix would be.

```
	case pmetric.MetricTypeExponentialHistogram:
		return compliantName + "/???", nil
```

**Comment by dashpole** [comment]
Thanks @alexvanboxel.  We are aware of this, and are coordinating with the Google Managed Prometheus team on adding support for exponential histograms.

**Comment by alexvanboxel** [comment]
I got it working locally; I've added the above code with `/distribution` and it works... at least for so far as I see (I can see something in Metrics Explorer. Need more exploration.

**Comment by dashpole** [comment]
It should work just fine with the regular metrics viewer.  I don't believe it will work with promQL yet.

**Comment by dashpole** [comment]
the GMP team has said that they plan to use the `/histogram` suffix we already use for regular histograms
