### ISSUE TITLE
resource detection fails for GCE running k3s

### ISSUE THREAD

**Issue by araji-collibra** [GoogleCloudPlatform/opentelemetry-operations-go#856]
The GKE detection logic while working in the GKE environment fails in the case of GCP compute running k3s (or kind but have only tested with k3s).
Because the environment variable KUBERNETES_SERVICE_HOST exists in that case, the resource detector assumes it is GKE but cannot pull the remaining GKE attributes (cluster name, etc ...) and does not fall through to GCE.

example of running the detector in k3s on compute engine instance:

`
root@ubuntu:/# ./detector
2024/06/05 20:55:29 Failed to detect GCP resources: partial resource: [metadata: GCE metadata "instance/attributes/cluster-location" not defined metadata: GCE metadata "instance/attributes/cluster-name" not defined]

root@ubuntu:/# unset KUBERNETES_SERVICE_HOST

root@ubuntu:/# ./detector
2024/06/05 20:58:20 Detected GCP resources: cloud.account.id=xxxx,cloud.availability_zone=us-east1-b,cloud.platform=gcp_compute_engine,cloud.provider=gcp,cloud.region=us-east1,gcp.gce.instance.hostname=somehost.internal,gcp.gce.instance.name=nstance1,host.id=3169418256728646889,host.name=myhostname,host.type=projects/98765432/machineTypes/e2-standard-16
`

**Comment by dashpole** [comment]
Thanks @araji-collibra for the report. I'm still trying to find time to fix this.

**Comment by dashpole** [comment]
The "on GKE" check should make sure the GKE cluster name is available.  I'll work on this soon
