### ISSUE TITLE
Typo in `intToDouble` feature gate naming

### ISSUE THREAD

**Issue by chingis-fiskil** [GoogleCloudPlatform/opentelemetry-operations-go#869]
Description
-
https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/844 introduced an option to convert all collected metrics from int to double. There is a typo in feature gate naming (which seemingly renders it unusable).

```diff
- "exporter.googlemanagedpromethues.intToDouble",
+ "exporter.googlemanagedprometheus.intToDouble",
```

**Comment by damemi** [comment]
Fixed by #870
