### ISSUE TITLE
Map OpenTelemetry resources to Cloud Monitoring resources when injecting resource data into spans

### ISSUE THREAD

**Issue by james-bebbington** [GoogleCloudPlatform/opentelemetry-operations-go#88]
See full description here: https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/84/files

**Comment by dashpole** [comment]
We have this now: https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/e2cce7b04a10906fca4fd38b95ba824a085d61e2/exporter/trace/trace_proto.go#L121
