### ISSUE TITLE
Document lack of support for deny listing in resource_filters (or add support).

### ISSUE THREAD

**Issue by bwplotka** [GoogleCloudPlatform/opentelemetry-operations-go#887]
Customers often try catch-all attachment of all resource attributes to all labels, which is a bad idea (cardinality, little usefulness, WIP work on supporting this better on PromQL).

```
exporters:
  googlemanagedprometheus:
    metric:
      resource_filters:
        regex: ".*"
```

One way of reducing the spread is to deny list attributes which are problematic. It's tempting to use Perl syntax like `regex: "^(?!process.command_args$).*$" ` to achieve it. This is not possible in RE2/Perl regexp in [Go that has linear compute guarantee](https://stackoverflow.com/questions/26771592/negative-look-ahead-in-go-regular-expressions). 

So some alternatives would be to replace regexp pkg with something more expensive (wouldn't recommend) or add "deny: true/false" filtering option to yaml (better).

However, I would propose we clearly make this as an anti pattern and officially document NOT supporting this. Customers should add those labels carefully one by one IMO, especially given our work to make this much smoother in the future.

Internally tracked as b/352682632

**Comment by dashpole** [comment]
Here is the docs that a user was following: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/googlemanagedprometheusexporter#root-causing-timeseries-collisions
