### ISSUE TITLE
unable to use OpenTelemetry asynchronous metric instruments

### ISSUE THREAD

**Issue by liiling** [GoogleCloudPlatform/opentelemetry-operations-go#89]
Hi! I'm trying to create a demo using OpenTelemetry with GCP monitoring backend.

When instrumenting with OpenTelemetry's async metric instuments, only ValueObserver seems to work, while SumObserver and UpDownSumObserver both give me the following error:
> Metrics Accumulator error: rpc error: code = InvalidArgument desc = Request was missing field metricDescriptor.metricKind: The descriptor does not have the metric kind set.

Is there any plan on fixing this? I'd be happy to contribute.

**Comment by nilebox** [comment]
Hi, this does look like a bug, though I don't have enough context.

> I'd be happy to contribute.

If you can submit a PR fixing this issue, I can help with getting it reviewed and merged.
Otherwise, could you please share a code example reproducing this issue?
