### ISSUE TITLE
Add cloud monitoring exporter for open-telemetry metrics

### ISSUE THREAD

**Issue by rghetia** [GoogleCloudPlatform/opentelemetry-operations-go#9]
equivalent of [stackdriver exporter for opencensus](https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver) metrics.

**Comment by rghetia** [comment]
@ymotongpoo , do you think you could have it ready by the end of next week?

**Comment by ymotongpoo** [comment]
I try it but my guts feeling says it is hard.

**Comment by mujtaba-ahmed12** [comment]
@ymotongpoo any update on this issue?

**Comment by ymotongpoo** [comment]
Yes, I'm working on it. It's taking time longer than expected due to COVID-19.

**Comment by mujtaba-ahmed12** [comment]
I have bandwidth over weekends. If you allow, I can help you in this.

**Comment by ymotongpoo** [comment]
@mujtaba-ahmed12 Thank you for the offer. I'm working on the port in collaboration with @rghetia now and it's getting closer, so I appreciate your patience for a bit more. Thank you!

**Comment by ymotongpoo** [comment]
The basic feature is merged in #24

**Comment by ymotongpoo** [comment]
Close this issue as it was merged
