### ISSUE TITLE
Writing timeseries fails due to invalid argument error

### ISSUE THREAD

**Issue by shouichi** [GoogleCloudPlatform/opentelemetry-operations-go#98]
We tried to instrument http handlers using `go.opentelemetry.io/contrib/instrumentation/net/http` and got the following error.

```
2020/09/17 05:36:44 rpc error: code = InvalidArgument desc = Request was missing field timeSeries.
2020/09/17 05:37:44 rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: Field timeSeries[0].metric.labels had an invalid value of "http.scheme": Label key contains invalid characters.: timeSeries[0]; Field timeSeries[1].metric.labels had an invalid value of "http.server_name": Label key contains invalid characters.: timeSeries[1]; Field timeSeries[2].metric.labels had an invalid value of "http.host": Label key contains invalid characters.: timeSeries[2]
```

The version we use is 7f2025af52931b2969faf09e998dd0731e8c9266.

**Comment by nilebox** [comment]
> Field timeSeries[0].metric.labels had an invalid value of "http.scheme": Label key contains invalid characters.

Looks like we need to rename the label keys, e.g. replace `.` with `_` in the exporter, since these format limitations are specific to Cloud Monitoring APIs.

**Comment by nilebox** [comment]
As far as I understand, the renaming can be done in https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/7f2025af52931b2969faf09e998dd0731e8c9266/exporter/metric/metric.go#L462

@shouichi would you be interested in sending a PR making this change? If you do so, please also make sure to add a unit test illustrating the issue.

**Comment by shouichi** [comment]
Sure, I'll take a look 👍
